Merge front end plugins feature
msupply-foundation/open-msupply pull request #2433
Opened 2023-11-03 03:30 UTC by mark-prins

Fixes #2084 

# 👩🏻‍💻 What does this PR do? 
 
Merge the front end plugins work into develop

# 🧪 How has/should this change been tested? 

Check that tests run and the site works. All individual elements have been tested in the PR process.

## 💌 Any notes for the reviewer?

## 📃 Documentation

- [ ] Plenty of docs to be created

2023-11-06 02:57 UTC, clemens-msupply commented
@mark-prins there are some conflicting files are you working on it? can merge them in...

2023-11-07 03:11 UTC, clemens-msupply requested changes
I tried to do a release build and run it. However, the frontend wouldn't load. It says the page js contains some invalid chars... I double-checked with the develop branch and its still working there. I guess it has something to do with the changed webpack config?

Could you please check if it runs for you or if its something on my machine? Hope this is not too difficult to track down...

2023-11-07 04:22 UTC, mark-prins commented
> Could you please check if it runs for you or if its something on my machine? 

I've checked out, run `yarn install` and can build the front end just fine. 
I'll ask if someone else can have a try as well. maybe it's linux?

2023-11-07 21:08 UTC, roxy-dao commented on server/repository/src/migrations/v1_04_00/mod.rs
> +        plugin_data::migrate(connection)?;
move to next version~?

2023-11-08 00:49 UTC, mark-prins commented
Killing this one off in favour of #2449

2023-11-08 00:49 UTC, closed without merging