1400 Can send internal orders without lines
msupply-foundation/open-msupply pull request #2461
Opened 2023-11-09 09:37 UTC by roxy-dao

Fixes #1400

# 👩🏻‍💻 What does this PR do? 
Disable confirmation buttons if no lines for:
- Outbound Shipment
- Inbound Shipment 
- Internal Order
- Prescriptions

# 🧪 How has/should this change been tested? 
- Create an invoice/requisition for any of the above
- See that the status confirmation button is disabled

2023-11-13 23:03 UTC, Chris-Petty requested changes
Code looks legit but I have not tested yet. Do omSupply devs typically checkout PR branches and do a run through? Depends on certainty?

From a design perspective (https://github.com/msupply-foundation/open-msupply/issues/1912) I'd have thought it'd be appropriate to give user feedback on why they can't change status. There's some ambiguity now on if it's a permission or form input error (no lines!).

2023-11-14 08:27 UTC, roxy-dao commented
> Code looks legit but I have not tested yet. Do omSupply devs typically checkout PR branches and do a run through? Depends on certainty?

Yup!

> From a design perspective (#1912) I'd have thought it'd be appropriate to give user feedback on why they can't change status. There's some ambiguity now on if it's a permission or form input error (no lines!).
Will see if I can add a tooltip for now...

2023-11-14 08:29 UTC, roxy-dao commented on client/packages/invoices/src/InboundShipment/DetailView/Footer/StatusChangeButton.tsx
>    ] = [
Both should work... Maybe @mark-prins might know why it was done like this?

2023-11-14 08:58 UTC, roxy-dao commented on client/packages/common/src/intl/locales/en/common.json
> +  "messages.no-lines": "Cannot change the status because there are no lines",
Tried to make this as generic as possible to use in 3 different areas

2023-11-14 08:58 UTC, roxy-dao commented on client/packages/common/src/ui/components/buttons/standard/SplitButton.tsx
> +    <Tooltip title={label}>
Tried adding the tooltip in StatusChangeButton but it wouldn't show up.. so added directly to here.

The rest of the file is just reformatting..

2023-11-15 01:55 UTC, Chris-Petty approved these changes
Did a quick test seems good!

2023-11-15 01:56 UTC, Chris-Petty commented on client/packages/invoices/src/InboundShipment/DetailView/Footer/StatusChangeButton.tsx
>    ] = [
FWIW I tried the change while I was testing and it seems typescript was happy

2023-11-15 03:48 UTC, merged