2504 Patient list loading issues
msupply-foundation/open-msupply pull request #2506
Opened 2023-11-20 09:38 UTC by roxy-dao

Fixes #2504 

# 👩🏻‍💻 What does this PR do? 
Passes the patients down to app buttons so that the patients api doesn't get called twice.

# 🧪 How has/should this change been tested? 
- [ ] Check if patients is getting called twice still

## 💌 Any notes for the reviewer?
Have answered the rest of the loading issues in the issue itself...

2023-11-20 09:39 UTC, roxy-dao commented on client/packages/common/src/types/schema.ts
> +  filter?: InputMaybe<StocktakeLineFilterInput>;
Not sure why this was missing when I generated..

2023-11-20 20:04 UTC, mark-prins requested changes
This will mean that if you filter the patient list, the csv export will only export the filtered view - which makes more logical sense, but is not like anywhere else on the site!

the main problem though is that it will use the current pagination, so the export will only export the current page of results, but we want it to export all results, hence using the `listAll` api call.

I tried replicating and I only have one patient API query being made - do you have a way to replicate the issue?

2023-11-20 20:27 UTC, clemens-msupply commented
@mark-prins can we only do the query when the export is done? I send you a datafile where I see the issue. However, the datafile is quite simple, so I am not sure why you are not seeing it...

I am getting two calls to patients when navigating to the patient list.

2023-11-20 20:36 UTC, roxy-dao commented
> This will mean that if you filter the patient list, the csv export will only export the filtered view - which makes more logical sense, but is not like anywhere else on the site!
> 
> the main problem though is that it will use the current pagination, so the export will only export the current page of results, but we want it to export all results, hence using the `listAll` api call.
> 
> I tried replicating and I only have one patient API query being made - do you have a way to replicate the issue?

Ah... true, I forgot to take pagination into account, but when I download the csv it loads all the patients regardless of pagination... the ''bug'' @clemens-msupply was stating in the issue in in all list views with the 'Export to CSV' button...

2023-11-20 20:37 UTC, mark-prins commented
only when the button onclick is called - that's why we are using the mutation. can't see any reason in the code why it would be called, nor any reason why it is different for the patients. the same pattern has been used everywhere else.

2023-11-20 20:38 UTC, roxy-dao commented
> only when the button onclick is called - that's why we are using the mutation. can't see any reason in the code why it would be called, nor any reason why it is different for the patients. the same pattern has been used everywhere else.

It happens everywhere...

2023-11-20 21:06 UTC, clemens-msupply commented
Yes right, listAll is a mutation and I also still see both queries. 

I am suspecting that the two queries happening because the filter/sort parameters are changing during the initial rendering. Not sure how to best avoid it.

The pagination and potentially the removal of the unneeded document data are IMHO the things that we should tackle first. Loading a little bit of data twice might then be acceptable if we can't find an easy solution for the double load.

2023-11-21 03:42 UTC, mark-prins commented
The problem is the query params handling - if you refresh the page, you only get one patients query made.
If you click on 'patients' in the nav, you'll see two. The first has no 'sort' option, the second does.

2023-11-21 19:11 UTC, roxy-dao commented on client/packages/programs/src/JsonForms/components/Search/SearchWithUserSource.tsx
> +  const { results, error: queryError, mutateAsync } = usePatientSearchQuery();
Changed to use patientSearch hook instead... feels more fitting...

2023-11-21 22:26 UTC, mark-prins approved these changes
👍  Works for me!

2023-11-22 01:29 UTC, clemens-msupply approved these changes
Works great thank you!

2023-11-22 08:29 UTC, merged