1402 Handle sortig
msupply-foundation/open-msupply pull request #2548
Opened 2023-11-28 11:52 UTC by raviSussol

Fixes #

# 👩🏻‍💻 What does this PR do? 
 

# 🧪 How has/should this change been tested? 

## 💌 Any notes for the reviewer?

## 📃 Documentation

_No user facing changes_

or

- [ ] Functional change 1
- [ ] Functional change 2

2023-11-29 04:45 UTC, raviSussol commented on client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.ts
> -        'locationName',
Removing redundant field `Location` from the stocktake datatable

2023-11-30 23:14 UTC, mark-prins requested changes
Nice! Thanks @raviSussol - looking good!

A change request please.. 🙏 

The issue says 'invoice lines' but the sort is only applied for Inbound Shipments. can you add the AppBarButtons change to outbounds as well please?

2023-12-01 04:29 UTC, raviSussol commented
@mark-prins Ah.. my bad! Updated with 916d81781

2023-12-06 02:04 UTC, mark-prins approved these changes

2023-12-06 06:33 UTC, merged