Fix column widths in view stock within inventory
msupply-foundation/open-msupply pull request #2578
Opened 2023-11-30 03:57 UTC by fergie-nz

Fixes #2462

# 👩🏻‍💻 What does this PR do? 
Fixes the column widths of some columns of stock listview.

# 🧪 How has/should this change been tested? 
- [ ] view stock in Inventory
- [ ] See that columns don't jump when either name or batch names extend beyond the normal width of the columns. See issue #2462 for an example of column size jumping.

## 💌 Any notes for the reviewer?
There might be some other cases where fixing column widths is necessary to prevent jumping, I'm not sure.
I kept this change to a minimum by only changing the obvious jumping columns in the stock list view.

2023-11-30 05:40 UTC, mark-prins requested changes
I may be old, but I've still got it!

![jumpy-stock](https://github.com/msupply-foundation/open-msupply/assets/9192912/bf6bc660-6129-4b7a-b02e-7c2efc675b1a)

by which I mean, looks like we need to fix the widths of all columns.

an alternative would be to disable the `ViewportList` in `DataTable` - that's the cause of this. Though that was put in because the long tables were super slow to render on android, so we should probably retain it.

2023-12-05 02:53 UTC, fergie-nz commented
What do you think of this?

I feel a bit strange fixing the widths when I think about different devices using the table, and with the reliance on tooltips which won't work on tablet.

But perhaps still better?

I've also added fixing widths for plugin columns to avoid duplication / reliance on specifying fixed widths there.

2023-12-06 02:00 UTC, mark-prins requested changes
I'm also a little reluctant to fix the widths in this way.. but it does fix the problem.
On reflection, I think best not to force the plugins though - as it is the plugin will need to specify a width. Why not just require them to set a minWidth and maxWidth?

What about making the column creation easier by [doing this](https://github.com/msupply-foundation/open-msupply/compare/2462-fix-jumping-stock-columns...2462-fix-jumping-stock-columns(column-width))?

2023-12-06 03:10 UTC, fergie-nz commented on client/packages/system/src/Stock/ListView/ListView.tsx
> +    ...pluginColumns.map(column =>
Perfect! Sounds good.

2023-12-08 01:59 UTC, mark-prins approved these changes

2023-12-11 20:30 UTC, merged