2452 name merging name link and invoice
msupply-foundation/open-msupply pull request #2585
Opened 2023-12-05 15:38 UTC by roxy-dao

Fixes #2452

# 👩🏻‍💻 What does this PR do? 
- Migration to add `name_link` table. 
- Migration to remove `invoice.name_id` and add `invoice.name_link_id`
- Migrations to recreate (for sqlite since can't drop views) and update (for postgres) triggers for invoice and invoice lines. 
- Fixed tests that rely on previous `invoice.name_id` 

# 🧪 How has/should this change been tested? 
- [ ] Run tests.
- [ ] Make sure invoice functionality is still working as intended.

2023-12-06 01:46 UTC, andreievg commented on server/repository/src/db_diesel/name_link_row.rs
> +    pub async fn find_one_by_id(&self, item_link_id: &str) -> Result<NameLinkRow, RepositoryError> {
name_link_id

2023-12-06 23:13 UTC, Chris-Petty requested changes
Pretty much good to go! Just found one thing seeming off...

2023-12-06 23:13 UTC, Chris-Petty commented on server/repository/src/db_diesel/invoice_row.rs
> +                    .and(name_link_id.eq(name)),
This seems suss to me - should really be on `name_link::name_id` in some manner and this doesn't seem like that, will have to look again in rust analyser...

All that said, the only place this function is called is in a test anyway, but I can see need to see all outbound shipments for a particular customer/patient. Though... I am curious why there is no equivalent `InboundShipmentRowRepository`? Is `OutboundShipmentRowRepository` actually not used outside of tests? Can we just remove it? I have a suspicion all shipments are just queried through the base invoice repository really.

2023-12-07 02:21 UTC, Chris-Petty commented on server/repository/src/migrations/v1_06_00/invoice_add_name_link_id.rs
> +            INSERT INTO changelog (table_name, record_id, row_action, name_id, store_id)
Noting that we're setting `name_link_id` onto `name_id`. Chatted to Andrei, to keep the trigger overhead low it's good to not doing a join on `name_link` to get the `name_id`, better to change `ChangelogRepository` to do the join. Good for another issue, I'll make it.

2023-12-07 23:41 UTC, Chris-Petty commented on server/repository/src/migrations/v1_06_00/invoice_add_name_link_id.rs
> +pub(crate) fn migrate(connection: &StorageConnection) -> anyhow::Result<()> {
Whatever you did seems to have fixed it hahahah

2023-12-08 00:04 UTC, Chris-Petty approved these changes
LGTM! ✨ I fixed conflicts with base, all tests passin'

2023-12-08 00:04 UTC, merged