886 add integration sync status progress
msupply-foundation/open-msupply pull request #2670
Opened 2024-01-03 05:56 UTC by fergie-nz

Fixes #886 

# 👩🏻‍💻 What does this PR do? 
Adds logging and visual display for progress of integration step of syncing.

Note it only works on the initialising sync step - not syncing of already initialised setups.

This is because existing sync integration is run in a transaction.

# 🧪 How has/should this change been tested? 
You can test this

## 💌 Any notes for the reviewer?
The tests aren't working on this branch.
They also aren't working on develop for sync (for me)

I'm not sure if I am exacerbating things, or if sync testing requires specific setup.

2024-01-03 06:00 UTC, fergie-nz commented on server/service/src/sync/synchroniser.rs
> -        info!("Delete Integration result: {:?}", deletes);
I assume these info flags are no longer necessary with logging added :)

2024-01-08 01:16 UTC, mark-prins requested changes
Looking great thanks!

much nicer having progress - thanks for wading through the back end code to sort this one out..

I have a fix for the test, and a suggestion.
Also had a look at the linked issue (#923) - that still crashes the server and I'd hoped that we could just show an integration error. Unfortunately `serde_json::from_str` does not return an error if one of the field translations panics, the server will simply die. I went down the rabbit hole for a bit and stopped.

Also wanted to have a look at getting the stats when running in operational mode, but have spent long enough!

2024-01-08 01:22 UTC, mark-prins commented
if it's helpful - my changes are in [this branch](https://github.com/msupply-foundation/open-msupply/compare/886-testing-branch...886-testing-branch(integration))

2024-01-10 20:23 UTC, mark-prins approved these changes
👍  thanks for changes! looks great

2024-01-11 02:09 UTC, andreievg reviewed
Looks like i haven't quite submitted a review I did yesterday, a few comments. I think we should really just be doing progress for integration only and only for upserts

2024-01-14 23:33 UTC, andreievg commented on server/service/src/sync/synchroniser.rs
>              sync_buffer.get_ordered_sync_buffer_records(SyncBufferAction::Upsert, &table_order)?;
@fergie-nz 

As you've mentioned in telegram, this is actually not trivial:

https://github.com/msupply-foundation/open-msupply/compare/886-add-integration-sync-status-progress...886-add-integration-sync-status-progress(Example-of-option-mut)

2024-01-15 21:03 UTC, Chris-Petty commented on server/service/src/sync/translation_and_integration.rs
> +            if true == initialisation {
Nit: initialisation is a boolean, ya don't need to compare it!

Nit within a nit: https://en.wikipedia.org/wiki/Yoda_conditions. That said there isn't really a disadvantage it just reads a bit funny in English, and arguably there _are_ advantages as stated on wikipedia! I didn't know WordPress actually states it as a convention!

2024-01-15 22:43 UTC, andreievg requested changes
Just wanted to flag a point from my last comment as change request rather then nit. Thanks @Chris-Petty for mentioning that it's unclear if it's just a comment.

Basically as per the telegram chat, I would be happy to approve if this is implemented:
https://github.com/msupply-foundation/open-msupply/compare/886-add-integration-sync-status-progress...886-add-integration-sync-status-progress(Example-of-option-mut)(Simplified)

In summary:
* Only record integration progress for upserts during initialisation (don't record it during normal operations or for delete)
* Only show integration progress during initialisation (in UI), I haven't actually checked this bit

2024-01-16 20:43 UTC, andreievg approved these changes
Looks good, thanks @fergie-nz

2024-01-16 20:46 UTC, merged