2830 currency selection for inbound shipment
msupply-foundation/open-msupply pull request #2902
Opened 2024-02-07 19:29 UTC by roxy-dao

Fixes #2830

# 👩🏻‍💻 What does this PR do? 
Allows users to select a currency in the side panel if foreign currency pref is turned on. 
![Screenshot 2024-02-08 at 08 15 14](https://github.com/msupply-foundation/open-msupply/assets/61820074/4a1ab8be-91ac-4be8-8a96-ddbf6397ac76)

Shows the currency code, rate and invoice total in the foreign currency.
![Screenshot 2024-02-08 at 08 15 26](https://github.com/msupply-foundation/open-msupply/assets/61820074/aef4e5d9-7ec7-449b-9baf-c938955e96c7)

Displays home currency price and foreign currency price in the detail views.
![Screenshot 2024-02-08 at 08 15 39](https://github.com/msupply-foundation/open-msupply/assets/61820074/e687359e-9a49-486d-87f4-f3230bd52e85)

# 🧪 How has/should this change been tested? 
- [ ] Must have store preference `Store: Able to issue in foreign currency` on
- [ ] Go to inbound shipments
- [ ] Add some lines
- [ ] Change currency (See side panel for prices)
- [ ] Click on a line and see the foreign currency price conversions next to cost/sell/total prices

## 📃 Documentation
- Foreign currency documentation for Inbound Shipment

2024-02-07 22:04 UTC, roxy-dao commented on client/packages/invoices/src/InboundShipment/DetailView/SidePanel/PricingSection.tsx
> +              isDisabled={!storeIssuesInForeignCurrency}
Should this also be disabled for transfers?

2024-02-08 22:48 UTC, Chris-Petty requested changes
@roxy-dao did you end up seeking advice on if you should be able to adjust currencies on inbound shipments?

I'll note that the original docs referenced in the epic don't do mSupply justice and there are more considerations which I assume aren't covered because they aren't in your tests:

- The preference "Store: Able to **issue** in foreign currency" implicitly only applies to outbound shipments, not inbound. So if replicating mSupply this isn't required in this feature.
- You can only edit the currency in an inbound shipment if the supplier is an external supplier, not an mSupply store (internal supplier). If the supplier is a store the drop down list is disabled. This feature only really makes sense for external suppliers as they may be an overseas supplier who are expecting to be paid in a foreign currency. Internal transfers of stock generally don't have any money exchanging, let alone in foreign currencies. 
- The rate itself should be editable. I believe this is so that you can enter the agreed exchange rate, which might differ from the latest value from the `currency` table.

Annoyingly it is hard to know what the expected behaviour is from mSupply, the docs don't often present the full picture so the only robust thing is to look and toy around with it (and often look at code to make sense of the madness). Feel free to hit me up I have many eons of experience in the old code 😅. Speaking of many things in mSupply we wish we could change but have been deferring fixing them there in favour of leaving open mSupply to do better, so directly following the example there is often not ideal! Really this should be captured at a design phase and recorded in the issue before development begins, so totally not on you but the process.

2024-02-09 01:21 UTC, roxy-dao commented
> * You can only edit the currency in an inbound shipment if the supplier is an external supplier, not an mSupply store (internal supplier). If the supplier is a store the drop down list is disabled. This feature only really makes sense for external suppliers as they may be an overseas manufacturer who are expecting to be paid in a foreign currency. Internal transfers of stock generally don't have any money exchanging, let alone in foreign currencies.

I did and also played around in mSupply and read docs, but apparently wasn't enough! 😆 Will make the changes~ thanks Chris!

2024-02-26 04:49 UTC, Chris-Petty requested changes
A few little things but works good overall!

Dunno why the foreign currency total is different from the grand total here? (Made a CI from central server to OMS remote, edited some cost prices)
![image](https://github.com/msupply-foundation/open-msupply/assets/7684221/dcba9841-d927-469e-bf7a-90d358ff065b)

2024-02-26 19:13 UTC, roxy-dao commented on client/packages/common/src/ui/layout/tables/components/Cells/CurrencyCell/CurrencyCell.tsx
> +    const formatCurrency = useFormatCurrency(currency as Currencies);
Yah, the hook call isn't new... did you want me to move it out?

2024-02-26 19:17 UTC, roxy-dao commented on client/packages/system/src/Currency/Components/CurrencyModal.tsx
> +  };
Think it was because it was doing something funky on my machine and this got it to keep the state but yah it's unnecessary XD

2024-02-26 19:21 UTC, roxy-dao commented on server/graphql/invoice/src/mutations/outbound_shipment/error.rs
>  }
No these messages are just for devs but fe can handle how the error is displayed

2024-02-26 19:24 UTC, roxy-dao commented
> A few little things but works good overall!
> 
> Dunno why the foreign currency total is different from the grand total here? (Made a CI from central server to OMS remote, edited some cost prices) 

Should the grand total be in FC? I thought it was supposed to be in the home currency. 
<img width="945" alt="Screenshot 2024-02-27 at 08 24 03" src="https://github.com/msupply-foundation/open-msupply/assets/61820074/52b0bb3c-e288-4b8f-97fd-62f9ec72f972">

2024-02-27 02:53 UTC, Chris-Petty commented on client/packages/common/src/ui/layout/tables/components/Cells/CurrencyCell/CurrencyCell.tsx
> +    const formatCurrency = useFormatCurrency(currency as Currencies);
Hmm nah IDK maybe bigger issue outside of this one, nvm.

2024-02-27 02:57 UTC, Chris-Petty commented
> > A few little things but works good overall!
> > Dunno why the foreign currency total is different from the grand total here? (Made a CI from central server to OMS remote, edited some cost prices)
> 
> Should the grand total be in FC? I thought it was supposed to be in the home currency. <img alt="Screenshot 2024-02-27 at 08 24 03" width="945" src="https://private-user-images.githubusercontent.com/61820074/307925293-52b0bb3c-e288-4b8f-97fd-62f9ec72f972.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMDI2ODUsIm5iZiI6MTcwOTAwMjM4NSwicGF0aCI6Ii82MTgyMDA3NC8zMDc5MjUyOTMtNTJiMGJiM2MtZTI4OC00YjhmLTk3ZmQtNjJmOWVjNzJmOTcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDAyNTMwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1MjA5MDMzNWNiZmQ4MWE1MjVkZjc4YWRmMDE3MDQ5ZjVjMWJlNmNlNDQxOTMyNWFjNDVhZDAxMDkwZjA1NTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BCM5II6eqToIc4xNG2AsJa5qLM88S0riq4roMn_IT7Q">

In my picture it IS in the home currency, but the FC amount is for some reason different to the grand total despite the exchange rate being `1`?

2024-02-27 03:01 UTC, roxy-dao commented
> > > A few little things but works good overall!
> > > Dunno why the foreign currency total is different from the grand total here? (Made a CI from central server to OMS remote, edited some cost prices)
> > 
> > 
> > Should the grand total be in FC? I thought it was supposed to be in the home currency. <img alt="Screenshot 2024-02-27 at 08 24 03" width="945" src="https://private-user-images.githubusercontent.com/61820074/307925293-52b0bb3c-e288-4b8f-97fd-62f9ec72f972.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMDI2ODUsIm5iZiI6MTcwOTAwMjM4NSwicGF0aCI6Ii82MTgyMDA3NC8zMDc5MjUyOTMtNTJiMGJiM2MtZTI4OC00YjhmLTk3ZmQtNjJmOWVjNzJmOTcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDAyNTMwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1MjA5MDMzNWNiZmQ4MWE1MjVkZjc4YWRmMDE3MDQ5ZjVjMWJlNmNlNDQxOTMyNWFjNDVhZDAxMDkwZjA1NTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BCM5II6eqToIc4xNG2AsJa5qLM88S0riq4roMn_IT7Q">
> 
> In my picture it IS in the home currency, but the FC amount is for some reason different to the grand total despite the exchange rate being `1`?

Just registered. Will check soon

2024-02-29 22:27 UTC, Chris-Petty approved these changes
LGTM

2024-02-29 22:36 UTC, merged