Feature/merging
msupply-foundation/open-msupply pull request #2906
Opened 2024-02-07 23:03 UTC by Chris-Petty

Fixes #2450

# 👩🏻‍💻 What does this PR do? 

Brings in the changes of item and name merging using `item_link` and `name_link` respectively. 

# 🧪 How has/should this change been tested? 

Good amount of automated test suites but for the manual pass:

- [ ] mSupply Desktop Central Serve (MDCS) r and an OMS android or desktop. Synced, but with OMS on an older version (without these changes - we want to ensure migration works correctly)
- [ ] Merge 2 items and merge 2 names on MDCS and sync. (This will ensure there are unprocessed merge records in the integration buffer of OMS)
- [ ] Migrate OMS to the latest version including these changes
- [ ] Check:
  - [ ] Item catalogue updated
  - [ ] Master lists updated
  - [ ] Stock take lines updated 
  - [ ] Stock lines updated
  - [ ] Requisition lines updated
  - [ ] In/outbound shipment lines and prescription lines NOT updated (the original name when the line was added should be preserved)
- [ ] Check the names appear merged in
  - [ ] Customers (My product knowledge betrays me, is there such a list in OMS UI?)
  - [ ] Suppliers
  - [ ] Shipments referencing merged name
  - [ ] Internal orders/Requisitions **Tricky, you probably don't have any to the merged name as you can't merge store names! And you can't make these records to regular names/external parties in OMS... yet**
  - [ ] Prescriptions
  - [ ] Barcodes
  - [ ] Patient encounters

## 💌 Any notes for the reviewer?

All the code here has been reviewed as it was merged into the feature branch, so detail isn't so important. We are still waiting on the integration tests to be fixed, problems identified should be done very soon.

## 📃 Documentation

Hmm nothing yet? Merging is still done by the user in legacy mSupply, so no real new functionality here.

2024-02-13 22:28 UTC, roxy-dao reviewed
![gif](https://media.tenor.com/Iccl_wfwIdwAAAAM/despicable-me-minions.gif)

Just a few changes below before this can be merged to develop (: mostly to do with indexes that were removed in 1.6~

2024-02-13 22:45 UTC, roxy-dao requested changes
Forgot to change 😆

2024-02-13 23:34 UTC, Chris-Petty commented on server/service/src/processors/transfer/shipment/mod.rs
> +            // MERGE: Ignore if invoice name_link_id points to store's name. Supplying to itself! (Can happen with names are merge into stores)
Do we even do TODOs? 😅

2024-02-13 23:38 UTC, Chris-Petty commented on server/repository/src/migrations/v1_06_00/indexes.rs
> -        CREATE INDEX index_stock_line_supplier_id ON stock_line (supplier_id);
Nice catch!

2024-02-13 23:39 UTC, roxy-dao commented on server/service/src/processors/transfer/shipment/mod.rs
> +            // MERGE: Ignore if invoice name_link_id points to store's name. Supplying to itself! (Can happen with names are merge into stores)
Eventually... maybe.. idk...

2024-02-14 00:58 UTC, Chris-Petty commented on server/repository/src/db_diesel/clinician_link_row.rs
> +impl Default for ClinicianLinkRow {
https://github.com/msupply-foundation/open-msupply/pull/2906/commits/fc5f65d88dfd74a65d36aa4ea4e102107d994691

2024-02-14 00:58 UTC, Chris-Petty commented on server/repository/src/db_diesel/item_link_row.rs
> +impl Default for ItemLinkRow {
https://github.com/msupply-foundation/open-msupply/pull/2906/commits/fc5f65d88dfd74a65d36aa4ea4e102107d994691

2024-02-14 00:58 UTC, Chris-Petty commented on server/repository/src/migrations/v1_06_00/patient_id_indices.rs
> -        CREATE INDEX index_program_enrolment_patient_id ON program_enrolment (patient_id);
https://github.com/msupply-foundation/open-msupply/pull/2906/commits/e6bfb3a729ee75da30b996f2af3657b7c40dc200

2024-02-14 00:59 UTC, Chris-Petty commented on server/repository/src/migrations/v1_06_00/indexes.rs
> -        CREATE INDEX index_stock_line_supplier_id ON stock_line (supplier_id);
https://github.com/msupply-foundation/open-msupply/pull/2906/commits/e6bfb3a729ee75da30b996f2af3657b7c40dc200

2024-02-14 01:09 UTC, Chris-Petty commented on server/repository/src/merging.md
> +Any difference is due to a merge has occurred, and updating the `name_link_id` would undermine a design goal of potentially being able to "unmerge" entities.
Is this better?

https://github.com/msupply-foundation/open-msupply/pull/2906/commits/b35e6a4499e30435ba5d92f22913f070f84f9ae1

2024-02-14 01:16 UTC, roxy-dao commented on server/repository/src/merging.md
> +Any difference is due to a merge has occurred, and updating the `name_link_id` would undermine a design goal of potentially being able to "unmerge" entities.
Heaps! Thanks ❤️

2024-02-14 01:27 UTC, roxy-dao approved these changes
Woooot~ thanks for the changes Chris (:

2024-02-14 01:32 UTC, merged

2024-02-14 01:33 UTC, Chris-Petty commented
One of the scarier merge button presses...