#3013 Outbound return SidePanel
msupply-foundation/open-msupply pull request #3235
Opened 2024-03-08 01:30 UTC by CarlosNZ

Fixes #3013

# 👩🏻‍💻 What does this PR do? 
 

Thought I'd get this in quickly before I finish for the day.

Bare bones side panel here, basically copied the elements you'd included in your one @lache-melvin :)

# 🧪 How has/should this change been tested? 

Side panel opens and closes -- not much else :) 

## 💌 Any notes for the reviewer?

See inline

2024-03-08 01:40 UTC, CarlosNZ commented on client/packages/invoices/src/Returns/DetailView/SidePanel/AdditionalInfoSection.tsx
> +  const { user } = data || {};
I copied this from your one, but there's no `user` node on either of our ReturnByNumber queries (that I could tell). So not sure how you got the user data to be a valid type. Can probably figure out before merging, just wanted to rush this out the door for now.

2024-03-08 03:15 UTC, lache-melvin requested changes
Looks great Carl :) Just the user part of the query to update, up to you whether to add the delete now or later 🚀

2024-03-10 22:31 UTC, CarlosNZ commented
@lache-melvin Righto, have updated the `user` node in the query. I see you've made an issue for delete lines mutation, so will leave that for now.

2024-03-10 23:08 UTC, lache-melvin approved these changes
Ah yep that issue is actually to delete lines within the return, not delete the return itself, but all good to get this in and do that separately!

2024-03-10 23:13 UTC, merged