Handle long column labels in table headers
msupply-foundation/open-msupply pull request #3310
Opened 2024-03-17 22:16 UTC by clemens-msupply

Fixes #3173 

# 👩🏻‍💻 What does this PR do? 
- Add an ellipsis to prevent label overflow
- Put the description in the header tooltip (to show the full label if the label is too long

![image](https://github.com/msupply-foundation/open-msupply/assets/88299195/2ed588fb-4102-4967-8780-e4e4fd8192e5)

# 🧪 How has/should this change been tested? 
Test as described in issue or set "label.location" to a long label

2024-03-17 22:18 UTC, clemens-msupply commented
@mark-prins now that I look at it was your intention to always have a line break after "Click to sort this column"? Seems to make more sense?

2024-03-18 23:19 UTC, mark-prins requested changes
Working very nicely! I have some suggestions to add..

* I noticed that `label.location` was in `replenishment` and `inventory` and this is not required, because it is also in `common`
* the tooltip should show regardless of the `showTooltip` boolean, it is possible to have a column that isn't sortable, doesn't have a description but does have a restricting width specified! In this case you only see
<img width="169" alt="Screenshot 2024-03-19 at 12 13 23 PM" src="https://github.com/msupply-foundation/open-msupply/assets/9192912/036de832-03e2-42c3-b060-14c77a4f8740">

instead of

<img width="287" alt="Screenshot 2024-03-19 at 12 14 03 PM" src="https://github.com/msupply-foundation/open-msupply/assets/9192912/f8368c41-d732-41da-be67-df312fd3b16b">

* the 'click to sort by' text would look better if the 'this column' was removed:

<img width="309" alt="Screenshot 2024-03-19 at 12 11 10 PM" src="https://github.com/msupply-foundation/open-msupply/assets/9192912/61fbd381-8f17-4919-80bf-2b7b488dba72">

I've put the changes into a [suggestion branch](https://github.com/msupply-foundation/open-msupply/compare/3173-column-label-overlap...3173-column-label-overlap(renaming)) as it touches a few files!

2024-03-18 23:29 UTC, clemens-msupply commented
Thanks I merged you branch!

2024-03-19 03:49 UTC, mark-prins approved these changes

2024-03-19 03:50 UTC, mark-prins commented
Looks good - thanks @clemens-msupply!

2024-03-19 18:44 UTC, clemens-msupply commented
Darn I started from develop, do we want to have it in 1.7?

2024-03-19 19:50 UTC, mark-prins commented
oh! didn't notice. yes, ideally 1.7 - but given that nothing is actually broken, I'm fine with it being in 2.0

2024-03-19 21:58 UTC, clemens-msupply commented
Ok I did a:
```
git rebase --onto release-1.7 develop
git push -f
```

2024-03-19 21:58 UTC, merged