Print QR code labels
msupply-foundation/open-msupply pull request #3322
Opened 2024-03-18 05:31 UTC by mark-prins

Fixes #3145

# 👩🏻‍💻 What does this PR do? 
 
Adds the setting to save a label printer - this is the bare minimum, you can save one per site, it's a network enabled printer only and we only support zebras.

The settings page was getting messy, so I've tidied that up with Accordions, and have moved the server version to be top right:

<img width="1279" alt="Screenshot 2024-03-18 at 5 09 08 PM" src="https://github.com/msupply-foundation/open-msupply/assets/9192912/13ef0f97-5d4f-41cb-aa4a-87592de3c3c3">

<img width="1261" alt="Screenshot 2024-03-18 at 5 09 01 PM" src="https://github.com/msupply-foundation/open-msupply/assets/9192912/63d9eedf-8807-4c65-89a5-c3439177e443">

The print button on the equipment detail page is now 'Print QR code' and will do just that

<img width="348" alt="image" src="https://github.com/msupply-foundation/open-msupply/assets/9192912/5742af10-669c-4bdb-8d47-3f0472f91245">

There's a success & an error toast on the print event.

# 🧪 How has/should this change been tested? 

I'm testing with a GK420t, the king of label printers.
The settings I'm using are

<img width="773" alt="Screenshot 2024-03-18 at 6 01 18 PM" src="https://github.com/msupply-foundation/open-msupply/assets/9192912/090b1b7c-44f4-4777-8c50-80013ca10bc9">

The label height affects the vertical offset, but I've done nothing more complex than that. The QR code size is affected by the data and the magnification factor, I've used settings which look ok on our labels.

Check that the QR prints and has the correct value.

## 💌 Any notes for the reviewer?

## 📃 Documentation

Part of the asset feature

2024-03-18 05:34 UTC, mark-prins commented on client/packages/common/src/ui/components/inputs/TextInput/NumericTextInput.tsx
> +      noFormatting = false,
adding this - without it the port number is reformatted at `9,100` which isn't what I want at all

2024-03-18 05:35 UTC, mark-prins commented on client/packages/host/src/Admin/DisplaySettings.tsx
> +import React from 'react';
this is just moved out of `Settings` which was the original file. 
All the new settings were created as their own component, so I'm doing the same with the display settings

2024-03-18 05:36 UTC, mark-prins commented on client/packages/host/src/Admin/LabelPrinterSettings.tsx
> +    labelHeight: 290,
the defaults of our printer 🤷

2024-03-18 05:39 UTC, mark-prins commented on server/service/src/print/jetdirect.rs
> +use anyhow::Result;
from the crate `zebrasend`

2024-03-21 23:26 UTC, jmbrunskill commented
I'm getting this error

![image](https://github.com/msupply-foundation/open-msupply/assets/8287373/52d33dba-b63b-4b2c-bc04-874024ce9078)

-> Access Denied

Which doesn't give me much to go on!

Added some logging to find

2024-03-22 12:25:00.434951000 [ERROR] <server::print:68>:No default store found for user, or default store is not active on current site

Would be good to display errors a bit better to at least have a path forward.
This seems like an unnecessary restriction? You can't print QR codes if you aren't in your default store?

2024-03-22 01:51 UTC, jmbrunskill requested changes
Awesome stuff Mark.
Not quite sure if I should approve or request changes :)

I think the idea that you have to be in your default store is a bit of an unnecessary restriction, but happy to be convinced otherwise.

Would also be keen to at least reference the JetDirect source in the code base given it a copy and paste, but think we might be better of making a structure a bit more specific to our needs? For example do you think we'll need to send SGD commands in future?

2024-03-22 01:51 UTC, jmbrunskill commented on server/service/src/print/jetdirect.rs
> +use anyhow::Result;
This confused me! But I get it now, you've copied this from https://github.com/fearful-symmetry/zebrasend/blob/main/src/cmd/jetdirect.rs
I think we should have a comment in the file referencing where we copied it from!

I don't think we need to implement all this stuff, especial things like guessing if we should timeout etc.
We only need the `print` method part for now right?

If we know exactly what command we're sending I think we could look for the response for that specific command rather than relying on guessing?

2024-03-22 01:51 UTC, jmbrunskill commented on server/service/src/print/jetdirect.rs
> +        self.send_command_and_print(data, &mut telnet, mode, Duration::new(0, 500))
```suggestion
        self.send_command_and_print(data, &mut telnet, mode, Duration::new(0, PRINTER_TIMEOUT))
```

2024-03-22 01:51 UTC, jmbrunskill commented on server/service/src/print/jetdirect.rs
> +        self.send_command_and_print(data, &mut telnet, mode, Duration::new(0, 500))
I wonder what worst case connection times might be for our clients? is 500ms enough?

2024-03-22 01:51 UTC, jmbrunskill commented on server/service/src/print/jetdirect.rs
> +        let mut telnet = Telnet::connect((self.addr.clone(), self.port), 512)?;
```suggestion
        let mut telnet = Telnet::connect_timeout((self.addr.clone(), self.port), 512)?;
```

You actually need to do something like 

SocketAddr::new(IpAddr::V4(Ipv4Addr::from_str(self.addr.clone())
                                .expect("Invalid address")), self.port)

But that could be done once and stored in the `Jetdirect` struct...

This isn't essential as it does seem to timeout after 60s for me anyway

2024-03-22 01:51 UTC, jmbrunskill commented on server/service/src/print/jetdirect.rs
> +use anyhow::Result;
I'd be temped to re-arrange this into something more taylored for our use case....

2024-03-22 01:51 UTC, jmbrunskill commented on client/packages/coldchain/src/Equipment/DetailView/AppBarButtons.tsx
> +        <ButtonWithIcon
```suggestion
        <LoadingButton
```
It's easy to double click this and print twice, would be good to avoid that...

2024-03-22 04:34 UTC, mark-prins commented on client/packages/host/src/Admin/LabelPrinterSettings.tsx
> +    labelHeight: 290,
nice idea - will see if there's something I can add

2024-03-25 02:12 UTC, mark-prins commented on server/service/src/print/jetdirect.rs
> +use anyhow::Result;
if you have a suggestion on how to restructure - happy to hear it!
for now, just thought to implement the simple POC version

2024-03-25 02:14 UTC, mark-prins commented on server/service/src/print/jetdirect.rs
> +    pub addr: String,
thanks - changed

2024-03-25 04:42 UTC, mark-prins commented
thanks for the review @jmbrunskill!

I've added in a test button, and propagated the errors, so we now get errors showing here and when printing:

https://github.com/msupply-foundation/open-msupply/assets/9192912/49899581-e3b9-4a76-9ef7-5d850e84e4f9


> I think the idea that you have to be in your default store is a bit of an unnecessary restriction, but happy to be convinced otherwise.

That had come from the cold chain. Didn't know that it was possible to not have a default store tbh! have simply removed all of that validation - you can now print if you have a valid token in a the auth cookie. I think that printing to a label printer is pretty low risk. 

> Would also be keen to at least reference the JetDirect source in the code base given it a copy and paste, but think we might be better of making a structure a bit more specific to our needs? For example do you think we'll need to send SGD commands in future?

Done - and have used SGD to get printer info for the test code 😉

2024-03-26 01:10 UTC, jmbrunskill approved these changes
Thanks for the changes, looks good to me!

2024-03-26 03:53 UTC, merged