2229 move navigation out of delete hooks
msupply-foundation/open-msupply pull request #3396
Opened 2024-03-24 20:33 UTC by roxy-dao

Fixes #2229

# 👩🏻‍💻 What does this PR do? 
Refactor to move all navigation out of hooks.

# 🧪 How has/should this change been tested? 
- [ ] Ensure that you still get navigated to new page when creating Inbound, Outbound, Stocktake, Requisition and Internal Orders

2024-03-27 01:08 UTC, clemens-msupply requested changes
Looks good, when through the usages and think you covered all of them.

One nitty change request. There is a mix of async and .then which makes it more verbose than necessary...

2024-03-28 01:39 UTC, roxy-dao commented on client/packages/inventory/src/Stocktake/DetailView/SidePanel.tsx
> +    await mutateAsync([stocktake]).then(() => {
[29c536e](https://github.com/msupply-foundation/open-msupply/pull/3396/commits/29c536e0c48b446a4300107cd2e3b5d29694b48b) 🙏🏻

2024-03-28 01:42 UTC, clemens-msupply commented on client/packages/inventory/src/Stocktake/DetailView/SidePanel.tsx
> +    await mutateAsync([stocktake]).then(() => {
Sorry I meant for all the other changes as well...

2024-03-28 01:49 UTC, roxy-dao commented on client/packages/inventory/src/Stocktake/DetailView/SidePanel.tsx
> +    await mutateAsync([stocktake]).then(() => {
Done for all the deletes... I need the numbers for creation...

2024-03-28 01:51 UTC, clemens-msupply approved these changes

2024-03-28 01:51 UTC, clemens-msupply commented on client/packages/inventory/src/Stocktake/DetailView/SidePanel.tsx
> +    await mutateAsync([stocktake]).then(() => {
thanks!

2024-03-28 01:53 UTC, merged