3018 invalid mapping of m supply transact.tax to oms invoice.tax
msupply-foundation/open-msupply pull request #3691
Opened 2024-04-29 00:29 UTC by roxy-dao

Fixes #3018

# 👩🏻‍💻 What does this PR do?
Rename tax to tax_rate to make it clearer that it isn't the tax amount. Should be compatible with OG 7.14 which is required for V2.0 anyways... Though tax_rate is the ratio so maybe better to just rename everything to tax_percentage? 

Note: OG's tax field which was being used is actually the tax_amount.

## 💌 Any notes for the reviewer?

# 🧪 Testing

- [ ] Make sure tests are still running
- [ ] Make sure tax can still be set in frontend

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

2024-05-03 03:31 UTC, clemens-msupply commented
We shouldn't really (never) change an existing api. Did you check if reports use it? I also don't use it in any of my scripts so it might be ok to rename it.

However, we could also just use tax_percentage in the service instead of tax and leave the api as it is. Or is there a strong reason to use tax_rate? The api mostly uses tax_percentage and where not we could add some docs comments.

> Didn't rename it in invoice_stats though cause didn't wanna recreate the view again...

I think its worth doing this though. Or does this causes to many other changes?

2024-05-03 04:24 UTC, roxy-dao commented
> We shouldn't really (never) change an existing api. Did you check if reports use it? I also don't use it in any of my scripts so it might be ok to rename it.
> 
> However, we could also just use tax_percentage in the service instead of tax and leave the api as it is. Or is there a strong reason to use tax_rate? The api mostly uses tax_percentage and where not we could add some docs comments.
> 
> > Didn't rename it in invoice_stats though cause didn't wanna recreate the view again...
> 
> I think its worth doing this though. Or does this causes to many other changes?

Yeah, but tax can be confused with tax (amount)... =/ but if we never save tax amount I guess that'll be fine? Just confusing for new devs....

can use tax_percentage... was just using tax_rate to match OG, but I can use serde to rename. If we name it tax_percentage then then view doesn't need to be recreated

2024-05-05 20:32 UTC, clemens-msupply commented
I vaguely remember that we choose tax_percentage on purpose,  @andreievg, @mark-prins? At least we did it for the update input struct where we use `percentage`. Would have to rename it to rate there as well.

2024-05-05 21:27 UTC, roxy-dao commented
> I vaguely remember that we choose tax_percentage on purpose, @andreievg, @mark-prins? At least we did it for the update input struct where we use `percentage`. Would have to rename it to rate there as well.

Have renamed it to tax_percentage (:

2024-05-05 22:42 UTC, clemens-msupply requested changes
Just some smaller issues in the comments.

I think we should keep using `pub tax: Option<TaxInput>,` since TaxInput already contains percentage. We could even use TaxInput to update other tax related values in the future (if there are any).
There might be some renames like this in the service as well? 

So the frontend doesn't really support updating the tax? Only `client/packages/invoices/src/InboundShipment/api/api.ts` seemed to use it, right?

2024-05-05 22:42 UTC, clemens-msupply commented on server/graphql/invoice_line/src/mutations/outbound_shipment_line/service_line/update.rs
> +    tax_percentage: Option<TaxInput>,
This shouldn't be renamed, should it? percentage is already in the struct...

2024-05-05 22:42 UTC, clemens-msupply commented on server/graphql/invoice_line/src/mutations/outbound_shipment_line/line/update.rs
> +    tax_percentage: Option<TaxInput>,
Think this should stay tax (see other comment)

2024-05-05 22:42 UTC, clemens-msupply commented on server/graphql/invoice_line/src/mutations/inbound_shipment_line/service_line/update.rs
> +    tax_percentage: Option<TaxInput>,
Leave it as tax?

2024-05-05 22:42 UTC, clemens-msupply commented on server/graphql/invoice_line/src/mutations/inbound_shipment_line/line/update.rs
> +    pub tax_percentage: Option<TaxInput>,
Leave it as tax?

2024-05-05 22:42 UTC, clemens-msupply commented on server/graphql/invoice/src/mutations/outbound_shipment/update.rs
> +    tax_percentage: Option<TaxInput>,
Leave it as tax?

2024-05-05 22:42 UTC, clemens-msupply commented on server/graphql/invoice/src/mutations/inbound_shipment/update.rs
> +    pub tax_percentage: Option<TaxInput>,
Leave it as tax?

2024-05-05 22:50 UTC, roxy-dao commented on client/packages/invoices/src/InboundShipment/DetailView/modals/InboundServiceLineEdit/useServiceLineColumns.tsx
> +const taxPercentageCell = (props: CellProps<DraftInboundLine>) => (
Opps, sorry. Didn't double check mass rename 👀

2024-05-07 01:15 UTC, clemens-msupply approved these changes
Looks good thank you!

2024-05-07 01:49 UTC, merged