3679 simplify cold chain graphing
msupply-foundation/open-msupply pull request #3770
Opened 2024-05-06 00:57 UTC by jmbrunskill

Fixes #3679 
Fixes [#3090](https://github.com/msupply-foundation/open-msupply/issues/3090)
Fixes [#3283](https://github.com/msupply-foundation/open-msupply/issues/3283)

# 👩🏻‍💻 What does this PR do?

>Note: To Compare the two graphs, check out branch `3679-simplify-graph-compare-deleteme`

The cold chain graph now uses the normal temperatureLog query to get data, and shows all datapoints instead of an averaged summary. If there are too many datapoints, not all data is displayed and a warning is shown.

This makes the graph display much more consistently, is easier to understand from a code perspective, and from the point of view of the users.

Old:
![image](https://github.com/msupply-foundation/open-msupply/assets/8287373/cb9bab46-4ba1-4e30-8cd9-fdf65da9df40)

New:
![image](https://github.com/msupply-foundation/open-msupply/assets/8287373/2ca37696-18a0-4a73-82e8-75f93a645829)

Too much data...
![image](https://github.com/msupply-foundation/open-msupply/assets/8287373/5437a530-fa8e-4a2c-97dd-ddd4d3495f1b)

## 💌 Any notes for the reviewer?

Code has ended up a little bit messy sorry! Can clean up but figured better get some review first. For example it might be better to split some of the helper functions into another file similar to the old `useTemperatureChartData.ts`
Or maybe we've already spent too much time and just want to merge?

It's probably worth creating a custom graphql request for the temperature logs that avoids using loaders for performance, was going to do that but ran out of time.

We also talked about making sensors an auto complete in the filter section to make it easier to find a particular sensor. Particularly if you have too much data to display, which could potentially mean we don't see the sensor in the list at all.

Would be nice to show when a breach ended as was as when it starts. Would be possible to do something like that in future.

> This removes graphql/API functionality which is generally not recommended. However, we have no other known consumers of the chart data, and we're trying to simplify here, so reducing code and complexity is a win IMHO

# 🧪 Testing

- [ ] Setup a datafile with cold chain data, and view the cold chain charts under Cold Chain -> Monitoring
- [ ] Experiment with different timeranges and make sure the data aligns with what's in the database.
- [ ] Check that all the existing filter still work.
- [ ] Test if you get an performance issues on Android..

# 📃 Documentation
- [ X ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour

2024-05-06 23:13 UTC, jmbrunskill commented
FYI - Updated graph to include smaller dots based on review from @adamdewey

2024-05-07 00:39 UTC, roxy-dao commented
Rebase to V2.0.0 please~

2024-05-07 01:03 UTC, mark-prins requested changes
🥇  That is brilliant! thanks James - the chart is super quick now, and doesn't redraw randomly. This feels a lot more solid than it was!

I have a [suggestion branch](https://github.com/msupply-foundation/open-msupply/compare/3679-simplify-cold-chain-graphing...3679-simplify-cold-chain-graphing(quick-tidy)) with the tweaks I made - the request for change is the imports, I don't remember anything critical in there.

I agree about lifting things out of the TemperatureChart file, at > 500 lines it's larger than I like - but agree that enough time has been spent. I've just lifted out the tooltip, the rest of it I think we should leave as it is now.

One small gripe is that you only get a tooltip for one sensor but I think we just live with that

<img width="415" alt="Screenshot 2024-05-07 at 12 01 59 PM" src="https://github.com/msupply-foundation/open-msupply/assets/9192912/62a014a8-4f15-469f-a3b2-d6341327a11e">

<img width="379" alt="Screenshot 2024-05-07 at 12 01 55 PM" src="https://github.com/msupply-foundation/open-msupply/assets/9192912/a5234eb0-f2f0-4458-97b1-331b22345e63">

doesn't matter which line is highest (temperature wise, that is) - only the first shows the tooltip if there are multiple lines.

2024-05-07 01:04 UTC, mark-prins commented on client/packages/coldchain/src/Monitoring/ListView/TemperatureChart/TemperatureChart.tsx
> -  if (!hasData) {
weird. not see that change now - your original had the no data message 🤷  don't know how I got that first image, but seems fine now.

2024-05-07 01:08 UTC, adamdewey commented
> doesn't matter which line is highest (temperature wise, that is) - only the first shows the tooltip if there are multiple lines.

This seems to work ok for me - the tooltip only appears on the dots, so if you hover horizontally it will alternate between the lines depending on which dot it is next horizontally. 

At least, it works on tablets like that...

2024-05-07 01:50 UTC, mark-prins commented
> This seems to work ok for me

I couldn't get it to show on the web version, didn't matter where I hovered it always showed the tip from the first sensor

2024-05-07 02:44 UTC, jmbrunskill commented
> > This seems to work ok for me
> 
> I couldn't get it to show on the web version, didn't matter where I hovered it always showed the tip from the first sensor

I think it is trying to find the `closest point` to the cursor but does seem a bit weird. Looked into getting crosshairs to work but didn't find a good example to steal. Was thinking about finding the closest point for each line and display that (similar to the look up the old graph did, but I think we really only want to do that if the points from the lines are really close together. Could be done in future I think, maybe worth creating a follow up issue incase we want invest more time in future...

2024-05-07 02:48 UTC, jmbrunskill commented on client/packages/coldchain/src/Monitoring/ListView/TemperatureChart/BreachIndicator.tsx
> +      sx={{ color: 'background.white', cursor: 'pointer', zIndex: 9999 }}
Yeah found that and forgot to remove...

2024-05-07 03:02 UTC, jmbrunskill commented on client/packages/coldchain/src/Monitoring/ListView/TemperatureChart/TemperatureChart.tsx
> +import { Dot, XAxisProps } from 'recharts';
I think this is done in your suggestion branch right? Anything more for me to do?

2024-05-07 03:23 UTC, mark-prins commented on client/packages/coldchain/src/Monitoring/ListView/TemperatureChart/TemperatureChart.tsx
> +import { Dot, XAxisProps } from 'recharts';
no more to do thanks. I did the suggestion after the comment 😄

2024-05-07 03:23 UTC, mark-prins approved these changes
👍 Looks great! thanks James

2024-05-07 03:27 UTC, roxy-dao commented
Please rebase before merging (:

2024-05-07 03:31 UTC, mark-prins commented
this is me, trying to view the Q tag tooltip:


https://github.com/msupply-foundation/open-msupply/assets/9192912/f18fefca-f80a-4d37-9a4e-1a9539a8c060

2024-05-07 04:52 UTC, merged