3866 add support for registering new cce category cold rooms and freezer rooms
msupply-foundation/open-msupply pull request #3970
Opened 2024-05-21 07:14 UTC by jmbrunskill

Fixes #3866
Fixes #3929
Fixes #3866

# 👩🏻‍💻 What does this PR do?

Adds the asset properties that can be entered for Cold Rooms & Fridge Freezers

## 💌 Any notes for the reviewer?

For the catalogue items we also need to add new properties but thinking I might leave them till after re-factoring those? 

For Cold Rooms we need 

- Energy source
- Refrigerant type(s)
- 
See
- [ ] #3971
- [ ] #3973 

# 🧪 Testing

- [ ] Create freezers and cold room using all the new asset catalogue items (E001/SOMETHING)
- [ ] Check the correct properties show up in the summary page

# 📃 Documentation

- [X] **Part of an epic**: documentation will be completed for the feature as a whole

2024-05-22 04:00 UTC, mark-prins requested changes
Working nicely! thanks - just had a postgres thing to change.

Also wondered if we can we make the property name wider?

<img width="690" alt="image" src="https://github.com/msupply-foundation/open-msupply/assets/9192912/e227f3a0-284d-4cfd-aee3-dccc1242c1ba">

2024-05-22 04:00 UTC, mark-prins commented on server/repository/src/migrations/v2_01_00/assets/asset_property_data.rs
> +        INSERT INTO asset_property (id, key, name, value_type, allowed_values, asset_class_id, asset_category_id) VALUES ('voltage_stabilizer', 'voltage_stabilizer', 'Voltage stabilizer (integrated,
Actually, while at it - I would capitalise the `Integrated,External,None` values. Do they need to be lowercase?

2024-05-22 04:11 UTC, adamdewey commented
I think we don't need the 'Integrated', 'External' or 'None' in the title of the property - should be fairly evident from the dropdown?

2024-05-22 23:32 UTC, jmbrunskill commented on server/repository/src/migrations/v2_01_00/assets/asset_property_data.rs
> +        INSERT INTO asset_property (id, key, name, value_type, allowed_values, asset_class_id, asset_category_id) VALUES ('voltage_stabilizer', 'voltage_stabilizer', 'Voltage stabilizer (integrated,
Yeah agreed, I fixed this on another branch but obviously forgot to run postgres tests here 🤦‍♂️

2024-05-23 05:05 UTC, mark-prins approved these changes
🤩  thanks for changes!

2024-05-26 22:52 UTC, merged