4086 add custom properties to cold chain equipment csv import
msupply-foundation/open-msupply pull request #4195
Opened 2024-06-19 02:28 UTC by fergie-nz

Fixes #4086 

# 👩🏻‍💻 What does this PR do?

Adds bulk import of custom fields to cold chain equipment

## 💌 Any notes for the reviewer?

You can try this out by importing new asset items.
Example csv should 

# 🧪 Testing

- [ ]  Go to Cold Chain -> Equipment
- [ ] Click import
- [ ] See additional custom property fields for asset import
- [ ] Try adding asset property fields on bulk import
- [ ] See bulk imported custom fields in database

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

2024-06-19 06:05 UTC, mark-prins requested changes
🎉  very nice! it's working well Ferg - just putting in a suggestion which I've added to [this branch](https://github.com/msupply-foundation/open-msupply/compare/4086-add-custom-properties-to-cold-chain-equipment-csv-import...4086-add-custom-properties-to-cold-chain-equipment-csv-import(suggestion))

I think it's nicer, but see what you think

2024-06-19 21:37 UTC, fergie-nz commented on client/packages/coldchain/src/Equipment/ImportAsset/UploadTab.tsx
> +} from 'packages/system/src/Asset/api';
Apologies Mark I think you've asked me the same thing 20 times now!

2024-06-19 22:27 UTC, fergie-nz commented
> 🎉 very nice! it's working well Ferg - just putting in a suggestion which I've added to [this branch](https://github.com/msupply-foundation/open-msupply/compare/4086-add-custom-properties-to-cold-chain-equipment-csv-import...4086-add-custom-properties-to-cold-chain-equipment-csv-import(suggestion))
> 
> I think it's nicer, but see what you think

Nice Mark! Yes looks great, I like moving generic function into utils file

2024-06-20 00:37 UTC, mark-prins approved these changes
Cool - thanks for changes Ferg! 
let's 🚢

2024-06-20 01:01 UTC, merged