Allow settings to be reset
msupply-foundation/open-msupply pull request #4490
Opened 2024-08-02 02:35 UTC by mark-prins

Fixes #4485

# 👩🏻‍💻 What does this PR do?

When the theme or logo settings are disabled, the value is set to an empty string. The GQL endpoint was interpreting empty as the same condition as a matching hash i.e. no change required on the client.

This change is to distinguish those two cases. Now the GQL query will only return `null` when the hash matches.
The original bug is this:

* set a custom theme or logo in one browser
* browse to the site in another browser
* clear the setting in the first browser

in the second browser - it requests display settings. It get a response of 

```
{
  "data": {
    "displaySettings": {
      "customTheme": null,
      "customLogo": null
    }
  }
}
```

which the client app interprets as 'no change required' and therefore it retains the customised logo and/or theme.

This change allows the second browser to get an empty string response, which it then uses to update its display settings. 

## 💌 Any notes for the reviewer?

# 🧪 Testing

- [ ] set settings in one browser, login in another, clear in first browser, return to second. you will likely need to reload page to get the changes to show (not ideal but better than it was!)

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

2024-08-02 04:18 UTC, andreievg approved these changes
Looks good to me, thanks

2024-08-02 05:15 UTC, mark-prins commented on server/service/src/rnr_form/tests/finalise.rs
> +        // let last_requisition_number = RequisitionRowRepository::new(&context.connection)
there were complaints. so I've commented out 🤷

2024-08-02 05:15 UTC, mark-prins commented on server/repository/src/mock/rnr_form.rs
> +        adjusted_quantity_consumed: 7.0,
popped these in to fix the tests

2024-08-02 05:16 UTC, mark-prins commented on server/service/src/rnr_form/tests/insert.rs
> +        assert_eq!(form_lines[0].average_monthly_consumption, 4.026696329254727); // (5 * 31 / 30) (A) + (7 * 31  30) (B) + 0 (this period) / 3
offroad: update to fix the tests

2024-08-02 05:16 UTC, mark-prins commented on server/service/src/sync/test/test_data/rnr_form_line.rs
> +        "previous_average_monthly_consumption": 0.0
offroad: popped these in to fix the tests

2024-08-02 05:19 UTC, andreievg requested changes
oops, sorry my approval was just for the display settings, will have a look at other changes in a bit

2024-08-05 03:19 UTC, andreievg approved these changes
Thanks @mark-prins, looks good as far as i can tell

2024-08-06 04:06 UTC, merged