4116 catalogue items list is querying twice for each render
msupply-foundation/open-msupply pull request #4669
Opened 2024-08-22 17:32 UTC by roxy-dao

Fixes #4116

# 👩🏻‍💻 What does this PR do?
Fix itemWithStats being called twice 

# 🧪 Testing

- [ ] Go to item page and check network to see if api still being called twice

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

2024-08-22 17:32 UTC, roxy-dao commented on client/packages/system/src/Item/ListView/ListView.tsx
> +          navigate(
Sideqwest~

2024-08-23 00:53 UTC, CarlosNZ requested changes
Oops, this broke the items filter. 😢

![Screenshot 2024-08-23 at 12 52 39 PM](https://github.com/user-attachments/assets/ab6cc887-bde4-4a25-bfce-cc7d8f99a52d)

I'll try and fix it this afternoon.

2024-08-29 05:34 UTC, andreievg commented
I see that Laché assigned @CarlosNZ to fix, which leaves someone else to assign as reviewer, thank you

2024-08-29 05:49 UTC, CarlosNZ commented
@andreievg, have had a look at this.  Was planning to pause on it until I can inspect what's happening on Production server -- I suspect it may not be needed at all.

2024-08-30 02:30 UTC, CarlosNZ commented
@lache-melvin @andreievg 

So, it seems that this issue occurs on most of the List and Detail view components that are using the original API pattern. In the places where we've refactored it (Stock, Reports), it's behaving as it should (i.e. single GraphQL query on load). 

So I don't think we need to fix this specific case. The problem will naturally go away as we gradually refactor the API hooks to the new pattern.

Okay to close this?

2024-08-30 02:43 UTC, lache-melvin commented
Thanks for investigating Carl! Yeah that sounds good to me, another motivator to keep refactoring to the new pattern! 😁

2024-09-01 23:43 UTC, closed without merging

2024-09-01 23:43 UTC, CarlosNZ commented
Closing as per [above comment](https://github.com/msupply-foundation/open-msupply/pull/4669#issuecomment-2319718938)