4652 translate is immunisation program
msupply-foundation/open-msupply pull request #4716
Opened 2024-08-30 01:12 UTC by lache-melvin

Fixes #4652

# 👩🏻‍💻 What does this PR do?

Translates is_immunisation from mSupply 

You will need this mSupply branch: https://github.com/msupply-foundation/msupply/pull/15168

## 💌 Any notes for the reviewer?

# 🧪 Testing

- [ ] Per epic, set up at least one program as a master list
- [ ] Sync
- [ ] It shows in OMS central server in programs > immunisations 

# 📃 Documentation

- [x] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

2024-09-01 21:54 UTC, Chris-Petty requested changes
Not sure why but here test error:

```
failures:

---- sync::test::pull_and_push::test_sync_pull_and_push stdout ----
thread 'sync::test::pull_and_push::test_sync_pull_and_push' panicked at repository/src/db_diesel/master_list_name_join.rs:92:9:
assertion `left == right` failed
  left: Ok(None)
 right: Ok(Some(MasterListNameJoinRow { id: "A7A06D78361041448B836857ED4330C4", master_list_id: "87027C44835B48E6989376F42A58F7E3", name_link_id: "name_store_a" }))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Fine on develop though!

2024-09-01 21:54 UTC, Chris-Petty commented on server/service/src/sync/translations/program_requisition_settings.rs
> +        is_immunisation: master_list.is_immunisation.clone(),
nit: bool doesn't need cloning

2024-09-01 23:40 UTC, lache-melvin commented
> Not sure why but here test error:

Ah great catch thanks Chris, was only running the program tests 🙈 Forgot to update the other master list translation test data! 🙏

2024-09-02 00:05 UTC, Chris-Petty approved these changes
beaut

2024-09-02 00:16 UTC, merged