4792 report versioning schema changes
msupply-foundation/open-msupply pull request #4812
Opened 2024-09-18 02:00 UTC by fergie-nz

Fixes #4792 

# 👩🏻‍💻 What does this PR do?

Adds schema changes for report versioning

## 💌 Any notes for the reviewer?

Has dummy values for report sync translation from OG - but we will want to remove this in future. 

# 🧪 Testing

No testing required - no user changes

# 📃 Documentation

- [ ] [**Part of an epic**:](https://github.com/msupply-foundation/open-msupply/issues/4800)

2024-09-20 05:24 UTC, jmbrunskill requested changes
Thanks Fergus. SOrry for the long wait on the review!

It's all looking good to me, I've had a think about defaults and I think we're best to put defaults in for all of the new fields.

Have made suggestions, can you apply them and make sure everything compiles and tests correctly before we merge?

2024-09-20 05:24 UTC, jmbrunskill commented on server/service/src/sync/translations/report.rs
> +            code: todo!(),
```suggestion
            is_custom: true,
            version: 1.0.to_string(),
            code: id,
```
I don't think it's a good idea to check in code to develop with todo!() like this as it breaks tests which could cause people to spend time trying to fix, and/or we might ignore for ever.

Not a major, `todo!` is much better than putting something wrong it at least!
But I think we know what to put in now, so lets do that now... IMHO

2024-09-20 05:24 UTC, jmbrunskill commented on server/repository/src/db_diesel/report_row.rs
> +      code -> Nullable<Text>,
```suggestion
      code -> Text,
```
Lets go with not null?

2024-09-20 05:24 UTC, jmbrunskill commented on server/repository/src/db_diesel/report_row.rs
> +    pub code: Option<String>,
```suggestion
    pub code: String,
```

2024-09-20 05:24 UTC, jmbrunskill commented on server/repository/src/db_diesel/report_row.rs
> +            is_custom: Default::default(),
```suggestion
            is_custom: true,
```

2024-09-20 05:24 UTC, jmbrunskill commented on server/service/src/report/report_service.rs
> +            code: todo!(),
```suggestion
            is_custom: true,
            version: "1.0".to_string(),
            code: "report_1".to_string(),
```

2024-09-20 05:24 UTC, jmbrunskill commented on server/service/src/report/report_service.rs
> +            code: todo!(),
```suggestion
            is_custom: true,
            version: "1.0".to_string(),
            code: "report_base_1".to_string(),
```

2024-09-20 05:24 UTC, jmbrunskill commented on server/service/src/sync/test/test_data/report.rs
> +            code: None,
```suggestion
            code: REPORT_1.0.to_string(), // for now any thing sync'd from mSupply has the same id as code
```

2024-09-20 05:24 UTC, jmbrunskill commented on server/cli/src/cli.rs
> +                is_custom: todo!(),
I think we're probably ok to leave this as todo! as we're about to update the logic, but normally wouldn't want to have todo!() in main...

2024-09-23 05:02 UTC, fergie-nz commented on server/repository/src/migrations/v2_03_00/add_report_versioning.rs
> +                    ALTER TABLE report ADD COLUMN code TEXT;
Nice! Thanks James, sounds good.

I'm wondering about the specific use case where we might want to override a standard report with a custom report - would having an old standard report listed as a custom report be annoying in this case?

2024-09-23 05:16 UTC, fergie-nz commented
All tests passing now - though the intermittent failing of some tests in develop is increasingly making it awkward to check if tests are passing okay!

2024-09-23 06:10 UTC, jmbrunskill approved these changes
Looks good now, thanks Fergus!

2024-09-23 20:53 UTC, merged