4826 cold chain equipment module 'store' to show store name too instead of only store code
msupply-foundation/open-msupply pull request #4904
Opened 2024-09-29 23:27 UTC by roxy-dao

Fixes #4826

# 👩🏻‍💻 What does this PR do?
Show code and store name in store's search auto complete. 
![Screenshot 2024-09-30 at 12 01 50 PM](https://github.com/user-attachments/assets/24aaee93-13b7-4888-a1e8-ccc9687a0567)

## 💌 Any notes for the reviewer?
Do we want to change the store column to display the store name instead of store code since it has been commented that store code may make it difficult for user's to know where the asset is?

# 🧪 Testing

- [ ] Create new equipment
- [ ] Select store - see store code and name
- [ ] Go to equipment detail view
- [ ] Click on store
- [ ] See store code and name in selection
- [ ] Also try typing some of the name or code for filtering

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [x] **These areas should be updated or checked**: 
  1. Screenshots for equipment
  2.

2024-09-30 03:21 UTC, andreievg requested changes
Looks great, samll request StoreOptionRender should just be a component (don't need getStoreOPtionRenderer())

2024-09-30 03:21 UTC, andreievg commented on client/packages/system/src/Store/components/StoreSearchInput/StoreSearchInput.tsx
> +  const StoreOptionRender = getStoreOptionRenderer();
This should just be a component StoreOptionRender

2024-09-30 03:21 UTC, andreievg commented on client/packages/system/src/Store/components/StoreSearchInput/StoreSearchInput.tsx
> +const filterByNameAndCode = (options: StoreRowFragment[], state: any) =>
Instead of any can we put: FilterOptionsState<StoreRowFragment> ? Or can even add the filter inline in Autocomplete below

2024-09-30 03:21 UTC, andreievg commented on client/packages/coldchain/src/Equipment/ListView/CreateAssetModal.tsx
> +        storeName: store.storeName,
what does this do ? was it previously a bug ?

2024-10-01 04:13 UTC, andreievg approved these changes
Looks great, thanks @roxy-dao

2024-10-01 18:41 UTC, merged

2024-11-01 21:17 UTC, adamdewey commented
> Do we want to change the store column to display the store name instead of store code since it has been commented that store code may make it difficult for user's to know where the asset is?

Did this get included? 

I think it would be a lot easier to use with the name (or both name and code)

2024-11-03 18:39 UTC, roxy-dao commented
> > Do we want to change the store column to display the store name instead of store code since it has been commented that store code may make it difficult for user's to know where the asset is?
> 
> Did this get included?
> 
> I think it would be a lot easier to use with the name (or both name and code)

In the 2.4.0 test build