5064 translations for report print / export
msupply-foundation/open-msupply pull request #5065
Opened 2024-10-09 23:06 UTC by roxy-dao

Fixes #5064, #4995

# 👩🏻‍💻 What does this PR do?
Passes in the current language to the print api and also fixes wrapping of status chips in `expiring items` and `stock status` reports.

# 🧪 Testing

1.
- [ ] Change the language of the app
- [ ] Go to a report and try print
- [ ] The report should be in the language that you have selected
2. 
- [ ] Go to either `expiring items` or `stock status` report
- [ ] Change the size of the browser to be small
- [ ] The chips shouldn't wrap anymore

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

2024-10-09 23:08 UTC, roxy-dao commented on client/packages/system/src/Report/api/hooks/usePrintReport.ts
> +      currentLanguage,
Actually fix to get language through to printing / pdf

2024-10-09 23:08 UTC, roxy-dao commented on server/graphql/reports/src/print.rs
> +        *translation_service,
Sidequests...

2024-10-09 23:08 UTC, roxy-dao commented on server/reports/expiring-items/2_3_0/src/style.css
> +  white-space: nowrap;
Fix for chips wrapping

2024-10-11 04:58 UTC, andreievg requested changes
Looks great, but I am actually not a big fan of cloning the translation service, can we access it via reference ?

2024-10-11 05:06 UTC, roxy-dao commented
> Looks great, but I am actually not a big fan of cloning the translation service, can we access it via reference ?

Not cloning translation service? 🤔

2024-10-14 05:35 UTC, andreievg commented
> > Looks great, but I am actually not a big fan of cloning the translation service, can we access it via reference ?
> 
> Not cloning translation service? 🤔

I meant like this one, sorry should have been more specific 

https://github.com/msupply-foundation/open-msupply/compare/5064-Translations-for-report-print-/-export...5064-Translations-for-report-print-/-export(Avoid-cloning-translations-service)

2024-10-15 02:13 UTC, andreievg approved these changes
Thanks @roxy-dao, looks great

2024-10-15 02:20 UTC, merged