5088 manual requisition line new fields
msupply-foundation/open-msupply pull request #5178
Opened 2024-10-21 04:37 UTC by Chris-Petty

Fixes #5088

# 👩🏻‍💻 What does this PR do?

Adds fields and for manual requisitions. Sync translation updated. Basic gql added.

## 💌 Any notes for the reviewer?

A ramble about fields actually added
https://github.com/msupply-foundation/open-msupply/issues/5088#issuecomment-2425499748

> - [`days_out_of_stock` mobile uses `DOSforAMCadjustment`](https://github.com/msupply-foundation/mobile/blob/38602080d644736191062a02c024a1c7e804678c/src/sync/outgoingSyncUtils.js#L150-L151)
> - Desktop uses both `DOSforAMCadjustment` and `days_out_or_new_demand`. My suspicion here is that `days_out_or_new_demand` was the _much_ earlier field for _customer stock histories_ (basically a manual requisition) and it simply got missed? Also not ideal having a field with an "or" in its name. WHAT ARE YOU! My judgement atm is that using `days_out_or_new_demand` is correct, though perhaps at translation **push** we should populate both?
> - `Available` is not a field anywhere in OG or mobile. There is some weird circular mess that implies it's a field, but ultimately it's calculated by: `initial_SOH + incoming + additions - losses - outgoing` OG calculates this way as customisation for client - normally it's just SOH which seems bizarre. It is editable, but if you click on the value after editing it, it appears to jump back to the above custom calculation. IDK why this column is editable if calculations are going to override it (sometimes 🤪). Mobile does [something similar](https://github.com/msupply-foundation/mobile/blob/38602080d644736191062a02c024a1c7e804678c/src/database/DataTypes/RequisitionItem.js#L264-L271). I think, the code has been refactored till nothing is local to where it's used and the LSP can't help so 🤷‍♂️ can't spend too much time looking...
> - `MOS` is not a field anywhere in OG or mobile - it's just calculated from daily_usage
> - `Cust_loss_adjust` should be the net of `addition_in_units - loss_in_units` (and `initial_SOH - cust_loss_adjust >= 0` or riot) -> new field `inventory_adjustment`? Or not, because it's literally just one other field subtracted from another? We nonetheless can translate it and not add the field.
> 

# 🧪 Testing

Tests pass!

if you breakpoint OG and look at JSON pushed for a regular internal order, see the fields wow 
![image](https://github.com/user-attachments/assets/59b3a27a-a3d6-4079-95c1-ce631c8552f1)
(Do we normally push `optional` fields as null?)

2024-10-21 21:00 UTC, roxy-dao requested changes
Thanks Chris just a few comments below!

> - [`days_out_of_stock` mobile uses `DOSforAMCadjustment`](https://github.com/msupply-> > > foundation/mobile/blob/38602080d644736191062a02c024a1c7e804678c/src/sync/outgoingSyncUtils.js#L150-L151)
> - Desktop uses both `DOSforAMCadjustment` and `days_out_or_new_demand`. My suspicion here is that `days_out_or_new_demand` was the _much_ earlier field for _customer stock histories_ (basically a manual requisition) and it simply got missed? Also not ideal having a field with an "or" in its name. WHAT ARE YOU! My judgement atm is that using `days_out_or_new_demand` is correct, though perhaps at translation **push** we should populate both?

If mobile is using DOSforAMCadjustment for `days_out_of_stock` then we should use translate to that field instead. I agree having a column called `days_out_or_new_demand` does cause confusion cause what even is she? Days out or new demand? 😭 

> - `Available` is not a field anywhere in OG or mobile. There is some weird circular mess that implies it's a field, but ultimately it's calculated by: `initial_SOH + incoming + additions - losses - outgoing` OG calculates this way as customisation for client - normally it's just SOH which seems bizarre. It is editable, but if you click on the value after editing it, it appears to jump back to the above custom calculation. IDK why this column is editable if calculations are going to override it (sometimes 🤪). Mobile does [something similar](https://github.com/msupply-foundation/mobile/blob/38602080d644736191062a02c024a1c7e804678c/src/database/DataTypes/RequisitionItem.js#L264-L271). I think, the code has been refactored till nothing is local to where it's used and the LSP can't help so 🤷‍♂️ can't spend too much time looking...

If this field is a customisation on a client then would it be better to create a frontend plugin for this? 

> - `MOS` is not a field anywhere in OG or mobile - it's just calculated from daily_usage

Okay that's fine, can you add all the calculations into the UI issue.

> - `Cust_loss_adjust` should be the net of `addition_in_units - loss_in_units` (and `initial_SOH - cust_loss_adjust >= 0` or riot) -> new field `inventory_adjustment`? Or not, because it's literally just one other field subtracted from another? We nonetheless can translate it and not add the field.

Yup can you add it to the push translator? Thanks

2024-10-21 21:00 UTC, roxy-dao commented on server/service/src/sync/translations/requisition_line.rs
> +    pub cust_prev_stock_balance: f64,
Can you name these with the OMS names and just use serde rename to rename? Thanks

2024-10-21 21:00 UTC, roxy-dao commented on server/service/src/sync/translations/requisition_line.rs
> +            cust_prev_stock_balance: initial_stock_on_hand_units,
Can just use the oms name to populate

2024-10-21 23:33 UTC, Chris-Petty commented on server/service/src/sync/translations/requisition_line.rs
> +    pub days_out_or_new_demand: f64,
It do tho? (I'm about to change to days_out_of_stock in the legacy row tho)
https://github.com/msupply-foundation/open-msupply/blob/b654ba6800c8b5c2f1f68d2e255fe88443dade54/server/service/src/sync/translations/requisition_line.rs#L122

2024-10-21 23:34 UTC, roxy-dao commented on server/service/src/sync/translations/requisition_line.rs
> +    pub days_out_or_new_demand: f64,
OH, why did my mind just blur out the part after OR

2024-10-22 01:56 UTC, Chris-Petty commented
> Thanks Chris just a few comments below!
> 
> > * [`days_out_of_stock` mobile uses `DOSforAMCadjustment`]([https://github.com/msupply->](https://github.com/msupply-%3E) > > foundation/mobile/blob/38602080d644736191062a02c024a1c7e804678c/src/sync/outgoingSyncUtils.js#L150-L151)
> > * Desktop uses both `DOSforAMCadjustment` and `days_out_or_new_demand`. My suspicion here is that `days_out_or_new_demand` was the _much_ earlier field for _customer stock histories_ (basically a manual requisition) and it simply got missed? Also not ideal having a field with an "or" in its name. WHAT ARE YOU! My judgement atm is that using `days_out_or_new_demand` is correct, though perhaps at translation **push** we should populate both?
> 
> If mobile is using DOSforAMCadjustment for `days_out_of_stock` then we should use translate to that field instead. I agree having a column called `days_out_or_new_demand` does cause confusion cause what even is she? Days out or new demand? 😭
> 

Nah I think that we should use `days_out_or_new_demand` because virtually all OG logic uses it including with integration with other system(s) anyway (specifically overriding `DOSforAMCadjustment` with `days_out_or_new_demand`. It's tempting to populate both on translation push though?

> > * `Available` is not a field anywhere in OG or mobile. There is some weird circular mess that implies it's a field, but ultimately it's calculated by: `initial_SOH + incoming + additions - losses - outgoing` OG calculates this way as customisation for client - normally it's just SOH which seems bizarre. It is editable, but if you click on the value after editing it, it appears to jump back to the above custom calculation. IDK why this column is editable if calculations are going to override it (sometimes 🤪). Mobile does [something similar](https://github.com/msupply-foundation/mobile/blob/38602080d644736191062a02c024a1c7e804678c/src/database/DataTypes/RequisitionItem.js#L264-L271). I think, the code has been refactored till nothing is local to where it's used and the LSP can't help so 🤷‍♂️ can't spend too much time looking...
> 
> If this field is a customisation on a client then would it be better to create a frontend plugin for this?
> 

Ugh it's worse because this field is actually ambiguous too, hinted at in the comment above it:
https://github.com/msupply-foundation/open-msupply/blob/0a6d931d9d79eefbba0b5c81b31fb4a62face189/server/service/src/sync/translations/requisition_line.rs#L27-L28

I think the SOH is also calculated the same...

https://github.com/msupply-foundation/mobile/blob/38602080d644736191062a02c024a1c7e804678c/src/database/DataTypes/RequisitionItem.js#L264-L271

https://github.com/msupply-foundation/msupply/blob/dd2166b2031f5baadd9631c5965ae292ffc8e387/Project/Sources/Methods/createIntegrationObject.4dm#L72C1-L72C190

Sooooo the `Available` column is basically just SOH? This is clapped lol. And that last snippet has it being recalculated at integration which is just... wut. 

I think that SOH is meant OK OK I SCRATCHED DEEPER:

![image](https://github.com/user-attachments/assets/d78b81c8-d88f-4aab-8417-b47a06f5023d)

![image](https://github.com/user-attachments/assets/d3b860de-7823-40e9-ba80-f869a2f777bd)

Available literally is the `stock_on_hand` field. For a manual requisition it is the calculation as above. It probably shouldn't be editable: https://github.com/msupply-foundation/msupply/issues/15467

🤪 

> > * `MOS` is not a field anywhere in OG or mobile - it's just calculated from daily_usage
> 
> Okay that's fine, can you add all the calculations into the UI issue.
> 
> > * `Cust_loss_adjust` should be the net of `addition_in_units - loss_in_units` (and `initial_SOH - cust_loss_adjust >= 0` or riot) -> new field `inventory_adjustment`? Or not, because it's literally just one other field subtracted from another? We nonetheless can translate it and not add the field.
> 
> Yup can you add it to the push translator? Thanks

2024-10-22 02:14 UTC, roxy-dao commented
![fire](https://github.com/user-attachments/assets/567311cf-db42-4da8-ac04-40db2a65cf75)

2024-10-22 02:50 UTC, roxy-dao approved these changes
Thankie you

2024-10-22 03:15 UTC, merged