5171.1 response program requisition
msupply-foundation/open-msupply pull request #5183
Opened 2024-10-21 23:37 UTC by roxy-dao

Part 1 of #5171

# 👩🏻‍💻 What does this PR do?
- Adds `other_party_id` to the `requisition_in_period` view, so we can filter out requisitions made in the different periods by customers.
- Query to get program customers 
- Rename of current program_settings to indicate that it is for suppliers
- Prepare + map functions to get program settings for customers
   - The order types and periods for a program are filtered and grouped by customer since it is possible for multiple customers to have the same program master list and they should be able to order from periods that haven't been ordered from. The requisitions aren't filtered out by type as a customer can request a requisition for some period and this ensures that requisitions aren't created for the same order type and period. 
- Add endpoint to fetch customer program settings

# 🧪 Testing

- [ ] Have programs set up 
- [ ] Have customers that aren't stores
- [ ] Set up tags for your store and customers that aren't stores
- [ ] Call customerProgramRequisitionSettings endpoint

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [x] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

2024-10-21 23:48 UTC, roxy-dao commented on server/graphql/requisition/src/mutations/errors.rs
> +impl MaxOrdersReachedForPeriod {
Moved to errors file since both being used in customer and supplier program settings

2024-10-21 23:48 UTC, roxy-dao commented on server/repository/src/db_diesel/program_requisition/requisitions_in_period.rs
> +        other_party_id -> Text,
Needed to filter out requisitions by other party to group order types

2024-10-21 23:48 UTC, roxy-dao commented on server/service/src/requisition/program_settings/common.rs
> +use util::date_now;
File is a refactor to move common components out of original program settings

2024-10-21 23:48 UTC, roxy-dao commented on server/service/src/requisition/program_settings/customer_program_settings/map.rs
> +                    let order_types = order_types
Grouping customer with order types to allow different customers the ability to order from same order type if available

2024-10-21 23:48 UTC, roxy-dao commented on server/service/src/requisition/program_settings/mod.rs
> -use repository::{
Moved

2024-10-21 23:48 UTC, roxy-dao commented on server/service/src/requisition/program_settings/supplier_program_settings/prepare.rs
> -    // TODO confirm if they are strictly stores, i.e. can't make internal program order (requisition) to a non store supplier
Removed this comment because suppliers are already being filtered out by if they are a store in repo layer

2024-10-23 01:58 UTC, Chris-Petty requested changes
Looks all good! However I do want to see dsl aliases in the 🗑️ 😁

2024-10-23 03:11 UTC, Chris-Petty approved these changes
GOGOGO

2024-10-23 03:13 UTC, merged