#4917 Fix patches with nullable values
msupply-foundation/open-msupply pull request #5309
Opened 2024-11-04 23:16 UTC by CarlosNZ

Fixes #4917

# 👩🏻‍💻 What does this PR do?

Problem was caused by the `setNullableInput` function when passing a partial update object to the mutation function -- any properties that were not defined were getting set to `{value: null}` and by the nullable input function.

Have changed `setNullableInput` to require an explicit `null` value in order to set `null` in backend.

I'm pretty sure this doesn't break anything else -- have had a quick check and seems okay elsewhere.

See inline comments for other minor notes.

## 💌 Any notes for the reviewer?

We're actually not being particularly consistent with how we handle `null` updates. Some use the `setNullableInput` in the front-end, whereas other places send a full update object (with `null` values) and are handled by the GraphQL layer on the server (where `null` => `None`). It would be good to consolidate this at some point and have a standard pattern.

Personally, I don't like the use of `setNullableInput` -- formatting null values as `{value: null}` is an implementation detail of the GraphQL abstraction, so the front-end shouldn't even need to know about it. Ideally we could:
- send partial updates
- `null` values are treated as `null`/`None`
- `undefined` values are not updated

As I understand it, there's some complexity in the GraphQL layer that makes this not completely straightforward, so would need a bit of careful re-factoring -- something for another day...

# 🧪 Testing

- [ ] Go to Inventory -> View Stock and click on an item
- [ ] If the item doesn't have a location, set one, save, then exit back to the list
- [ ] Go back to the same item, change some other values (e.g. costs)
- [ ] Save, and ensure the "Location" is kept as-is
- [ ] Maybe check the behaviour in some other places where user can set `null` values and ensure no regressions

2024-11-04 23:22 UTC, CarlosNZ commented on client/packages/common/src/utils/functions/ApiUtils.tsx
> +  if (entity === null) return { value: null };
Classic error caused by the less strict equality operator (`==`). This returns true for `undefined` as well, so properties that were not defined were replaced with `null`s.

2024-11-04 23:22 UTC, CarlosNZ commented on client/packages/common/src/utils/functions/ApiUtils.tsx
> +  if (entity === undefined) return undefined;
Not completely required for this use case, but better to be explicit here. `!entity` would also match `0` or `""` .

2024-11-04 23:22 UTC, CarlosNZ commented on client/packages/system/src/Stock/api/hooks/useStockLine.ts
> +    setPatch({});
Unrelated, but something I noticed when testing. Best to clear the patch after update, so you start fresh with subsequent updates. (This was why the original "bug" didn't happen sometimes -- if you hadn't done something to clear the patch object, the original location would get updated, so no bug -- perhaps that's why you saw it "intermittently", @lache-melvin ?)

2024-11-05 20:16 UTC, jmbrunskill commented
It's a slightly different issue but Item Variant is also disappearing if you change price.

Can you investigate in this PR.

2024-11-05 20:22 UTC, jmbrunskill requested changes
Nullable Input changes All looks good.
Also had a poke around, only thing I found was that item_variant issue which doesn't appear to be nullable input related but is on the same screen.

Totally agree about your comments about consistency between full and partial updates, and potential to simiplify nullable inputs.

2024-11-05 21:05 UTC, CarlosNZ commented
> It's a slightly different issue but Item Variant is also disappearing if you change price.
> 
> Can you investigate in this PR.

Yeah, good catch. Needed to add additional check for the entity object being defined, but with an `undefined` value on it: b65180023b

I think the front-end is doing too much work here for implementation details that should be behind an abstraction layer on the server. Would be good to refactor this at some point. You think it's worth making a "refactor" issue?

2024-11-06 02:27 UTC, jmbrunskill commented
> I think the front-end is doing too much work here for implementation details that should be behind an abstraction layer on the server. Would be good to refactor this at some point. You think it's worth making a "refactor" issue?

Yup absolutely!

2024-11-06 02:28 UTC, jmbrunskill approved these changes
Looks good, thanks!

2024-11-06 20:28 UTC, merged