5100 import gaps data script
msupply-foundation/open-msupply pull request #5450
Opened 2024-11-18 05:41 UTC by jmbrunskill

Fixes #5100

# 👩🏻‍💻 What does this PR do?

Creates...

1. Master List for GAPS to provide item visibilty (will only exist in OMS Central)
2. `items`
3. `item_link` - Not synced should it be?
4. `item_variant` (for item variant and diluent variant)
5. 3 `packaging variant`s for each `item_variant`
6. If diluent is not bundled
7. Create diluent
8. Create diluent variant
9. Create item_bundle
10. Create diluent packaging variants (x3)

Have I missed something?

## 💌 Any notes for the reviewer?

Sorry for the messy code and writing in python, seemed like the fastest way to get something working.

There's probably a bit of data clean up or filtering to add.
For example if there a 0 or no `volume_per_unit` we're just loading that in, but maybe should exclude those items till we have the actual data for them???

Any other data cleanups we need to consider?

# 🧪 Testing

- [ ] Run the gaps_Inserts.sql script in your OMS Central Postgres Server
- [ ] Check that the item_variant, bundles, etc line up with the data here: https://docs.google.com/spreadsheets/d/1H_5_GMNdSN6_eLlRqZ7z4_3gx9spShwvb1NtLBrMEjQ
- [ ] It won't be possible to check everything but spot checking random things is a good idea...

# 📃 Documentation

- [X] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  12.

2024-11-18 05:42 UTC, jmbrunskill commented on server/gaps/asset_catalogue/migration.sql
> +INSERT INTO asset_class (id, name) VALUES ('fad280b6-8384-41af-84cf-c7b6b4526ef0', 'Cold chain equipment');
I added this too, as I believe we'll need to update this asset list soon...

2024-11-18 05:43 UTC, jmbrunskill commented on server/gaps/gaps_item_variants.csv
> +Item Universal Code,PQSVaccineID,VaccineType,VaccineTypeName,Manufacturer,CommercialName,PharmaceuticalForm,Presentation,DosesCount,ShelfLife,VaccinePreservative,AdministrationRoute,VaccineStorageTem
Exported from https://docs.google.com/spreadsheets/d/1H_5_GMNdSN6_eLlRqZ7z4_3gx9spShwvb1NtLBrMEjQ

2024-11-18 05:44 UTC, jmbrunskill commented on server/gaps/helpers.py
> +    print("INSERT INTO master_list_name_join (id, master_list_id, name_link_id) SELECT uuid_in(md5(random()::text || random()::text)::cstring), '43491ce9-bc89-4ee5-988d-9dbb2856e398', id FROM name_li
Should make the master list available to all names in the current sync site.
Make sure you sync the site first before running this script.
Seems unlikely that you're not have synced but still...

2024-11-18 22:12 UTC, lache-melvin requested changes
Script doesn't work on SQLite... are we safe to assume central server would always be running PG (probably right?)

I think I would benefit from a little more content in the readme 😁 

Perhaps we can put the .sql files in a `generated` folder? I don't think I mind committing them, nice not to need to run the generation scripts first, but good to be clear about what to do if you need to change any of the data.

> item_link - Not synced should it be?

No all good, links get created when items are inserted - once new items sync to other sites they'll create their own links 👍

2024-11-18 22:12 UTC, lache-melvin commented on server/gaps/gaps_insert_functions.py
> +    item_code = row['VaccineTypeName']
Typename might need to be included in item name, getting this with covid vaccines and rotavirus (codes are all different but this looks not great...) 
![Screenshot 2024-11-19 at 11 00 46 AM](https://github.com/user-attachments/assets/9b33eb10-ecad-43ba-9399-30e5b45dd05a)

2024-11-18 22:12 UTC, lache-melvin commented on server/gaps/gaps_insert_functions.py
> +        item_variant_name = row['VaccineTypeName']
NIT, we can improve later... but maybe a bit much duplication 😁 

<img width="427" alt="Screenshot 2024-11-19 at 11 11 14 AM" src="https://github.com/user-attachments/assets/cd559b7e-0128-4c5c-b42b-1e36fffabd6d">

2024-11-19 02:42 UTC, lache-melvin commented
Oh forgot to mention in review - business logic prevents duplicate item variant names, but this script is creating duplicates. I guess they do have duplicate names in the catalogue, but we need to make a decision either to include something unique in the variant names here, or to show more info in the item variant select dropdowns (currently would be no way to tell which variant you are bundling etc?)

2024-11-21 02:24 UTC, jmbrunskill commented
@adamdewey do you want to try to run the SQL inserts here on you Open mSupply Central Server? https://github.com/msupply-foundation/open-msupply/blob/13c5d3d445a4e90b609506d186bd843db432e39b/server/gaps/items/generated/gaps_item_inserts.sql

Have a look to see if you see any issues with the translation of the PQS Vaccine data.

2024-11-21 23:07 UTC, jmbrunskill commented
Just found a bug with this, running multiple times adds the items multiple times to the masterlist which creates some un-intended effects, we should delete the master list association on each run or check if the item exists on the master list before inserting...

2024-11-24 23:40 UTC, jmbrunskill commented
> Just found a bug with this, running multiple times adds the items multiple times to the masterlist which creates some un-intended effects, we should delete the master list association on each run or check if the item exists on the master list before inserting...

Fixed...

2024-11-25 01:05 UTC, lache-melvin requested changes
Looking good thanks James! Main request is to add the diluents/bundled items to the master list as well, so we can see those items separately 🙏 

Wonder if it's worth adding a carry over issue to sync the master list... would be nice just to enable GAPS items in another store too - though maybe that's more of a dev desire, instead of controlling what's seen by each store 😁

2024-11-25 01:06 UTC, lache-melvin commented on server/repository/src/migrations/v2_04_00/mod.rs
> +            Box::new(item_changelog::Migrate),
See you haven't resolved this comment, did you have a recommended plan here @jmbrunskill? Just leaving for now?

2024-11-25 02:01 UTC, jmbrunskill commented on server/repository/src/migrations/v2_04_00/mod.rs
> +            Box::new(item_changelog::Migrate),
Yup planning to just leave it for now.

2024-11-25 02:03 UTC, jmbrunskill commented
> Wonder if it's worth adding a carry over issue to sync the master list... would be nice just to enable GAPS items in another store too - though maybe that's more of a dev desire, instead of controlling what's seen by each store 😁

Yeah, I'm not 100% sure what is the 'correct' behaviour. I think we probably don't really want to use that master list for anything other than visibility, so while I was originally thinking that, now I'm thinking. Maybe the Central Server should have a special show hidden items button similar to mSupply?

2024-11-25 02:24 UTC, adamdewey commented
@jmbrunskill  Ah, good point - I was imagining there would be a Master List with all items on that are not visible to any stores, and then they would also add the items that they **are** using to a different Master List which is visible to stores?

2024-11-25 02:25 UTC, jmbrunskill commented
> @jmbrunskill Ah, good point - I was imagining there would be a Master List with all items on that are not visible to any stores, and then they would also add the items that they **are** using to a different Master List which is visible to stores?

Ok, that is essentially what we have. We have a masterlist with all the gaps items, but only on the OMS Central Server. If you want to use any of the items for other stores, you'll need to add them manually to a master list.

2024-11-25 02:30 UTC, adamdewey commented
I think that should be fine - as long as they're there somewhere it's pretty straightforward to add them to a new Master List

2024-11-25 02:41 UTC, jmbrunskill commented
@lache-melvin diluents are added to the master list now.
Doing this I found another small bug, as diluents were using the Vaccine Type Name not mSupply Item Name for lookups, that's fixed now too.

2024-11-25 02:42 UTC, jmbrunskill commented
FYI this does a decent job of clean up, although might delete non-gaps items so please don't run unless you're sure!
```
DELETE from bundled_item;
DELETE from packaging_variant;
DELETE FROM item_variant WHERE id not in (SELECT coalesce(item_variant_id,'noid') from stock_line)
AND id not in (SELECT coalesce(item_variant_id,'noid') from invoice_line)
AND id not in (SELECT coalesce(item_variant_id,'noid') from stocktake_line);
DELETE FROM master_list_line WHERE id not in (SELECT item_link_id FROM stock_line)
AND id not in (SELECT coalesce(item_link_id,'noid') from invoice_line)
AND id not in (SELECT coalesce(item_link_id,'noid') from stocktake_line);
DELETE FROM item_link WHERE id not in (SELECT item_link_id FROM stock_line)
AND id not in (SELECT coalesce(item_link_id,'noid') from invoice_line)
AND id not in (SELECT coalesce(item_link_id,'noid') from stocktake_line);
DELETE FROM item WHERE id not in (select item_id from item_link);
```

2024-11-25 22:58 UTC, lache-melvin approved these changes
Looks great thanks for all this James!!

2024-11-25 23:37 UTC, merged