5388 add error for reasons in manual requisition changes
msupply-foundation/open-msupply pull request #5456
Opened 2024-11-18 20:09 UTC by fergie-nz

Fixes #5388

# 👩🏻‍💻 What does this PR do?

Adds error when suggested quantity differs from requested quantity in response requisition if no reason provided.
Adds error handling and info toast to front end.

This also only occurs on program requisitions; non program requisitions won't have the option to add reasons.
(Side question - should non program requisitions allow for requested != suggested? I have in this case, but am realising now that I'm not certain.)

## 💌 Any notes for the reviewer?

No error handling on creation (because lines are created with no info and won't have requested quantities).

# 🧪 Testing

You can test this by:

- [ ] Adding a line to a program response requisition
- [ ] Change the requested quantity to be different from suggested without a reason
- [ ] See the error
- [ ] Add a reason for the change
- [ ] See no error when reason has been added and requested != suggested

- [ ] _(e.g.)_ Central Sync server with 1 Legacy Desktop remote site and 1 OMS remote site running this PR
- [ ] _(e.g.)_ This sample datafile: _google drive link_
- [ ] _(e.g.)_ Open a requisition with some lines
- [ ] _(e.g.)_ Make a couple invoices supplying some amount of those lines
- [ ] _(e.g.)_ Review that "issued" column is the sum of the amount already issued in invoices for this requisition

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

2024-11-18 20:10 UTC, fergie-nz commented on client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/hooks.tsx
> +            break;
Handling error toast inside hook.

I see there are a number of ways that we are handling errors - in the api, in the hooks, or in components. 

Would love to add some consistency to our patterns!

2024-11-19 02:11 UTC, roxy-dao requested changes
The inputs are saved onBlur, which means once you set a requestedQuantity != suggestedQuantity, the requestedQuantity won't change -> error propped, requestedQuantity doesn't get saved -> infinite loop of trying to change requestedQuantity but being unable to because of 'reason'

2024-11-21 01:19 UTC, roxy-dao requested changes
Hiiii. 

The change request was to remove the reason error check for lines from backend and implemented in frontend. I see that it is still there. The requested quantity cannot be updated at all because of the error. 

The expected behaviour is: If the user has entered a requested quantity that is different from the requested quantity then the reasons field should be highlighted to indicate to the user that this is now a required field.

For backend you can add the reasons check when the user tries to update the Requisition and the lines on the detail view can be highlighted. This will stop the user from being able to finalise the requisition without putting in reasons for the lines that need it.

Lemme know if you want to sit down and walk through this together (:

2024-11-21 01:19 UTC, roxy-dao commented on client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ResponseLineEdit.tsx
> +    reasonsLoading;
Why have you disabled requested with these extra conditions? Users should be able to input requested quantity if the Requisition hasn't been generated from an Internal Order

2024-11-24 19:09 UTC, roxy-dao commented on client/packages/requisitions/src/ResponseRequisition/DetailView/DetailView.tsx
> +                      { replace: true }
This should be removed. We don't wanna replace the history

2024-11-24 19:10 UTC, roxy-dao commented on client/packages/requisitions/src/ResponseRequisition/DetailView/Footer/StatusChangeButton.tsx
> +      console.log('errorMessage', errorMessage);
Remove console.log?

2024-11-24 20:48 UTC, fergie-nz commented
> The reasons being far right make it hard to see the error highlight since the user has to scroll all the way to the right to see it... but that can be discussed later >.>

yes agreed! I found that annoying too. I still wonder if error should prompt when the user first enters also.

I will make a carryover issue for this.

2024-11-24 21:50 UTC, roxy-dao commented
> > The reasons being far right make it hard to see the error highlight since the user has to scroll all the way to the right to see it... but that can be discussed later >.>
> 
> yes agreed! I found that annoying too. I still wonder if error should prompt when the user first enters also.
> 
> I will make a carryover issue for this.

Yup, I think highlighting the row on the page will also make it clear to the user that this needs to be inputted. The asterisk probably isn't obvious enough

2024-11-24 22:29 UTC, roxy-dao approved these changes
Cool thanks for changes Ferg

2024-11-24 22:34 UTC, merged

2024-11-25 00:08 UTC, fergie-nz commented
> > > The reasons being far right make it hard to see the error highlight since the user has to scroll all the way to the right to see it... but that can be discussed later >.>
> > 
> > 
> > yes agreed! I found that annoying too. I still wonder if error should prompt when the user first enters also.
> > I will make a carryover issue for this.
> 
> Yup, I think highlighting the row on the page will also make it clear to the user that this needs to be inputted. The asterisk probably isn't obvious enough

carryover issue: https://github.com/msupply-foundation/open-msupply/issues/5544