fixed show/hide all
msupply-foundation/open-msupply pull request #5475
Opened 2024-11-19 18:26 UTC by myspace20

Fixes #5396

# 👩🏻‍💻 What does this PR do?
This adds the show or hide all logic to the data table custom column picker, reported in the detailed view of any outbound shipment. Previously, the hide/show all checkbox existed but the logic was unavailable.

## 💌 Any notes for the reviewer?

# 🧪 Testing

- [ ] _(e.g.)_ Central Sync server with 1 Legacy Desktop remote site and 1 OMS remote site running this PR
- [ ] _(e.g.)_ This sample datafile: _google drive link_
- [ ] _(e.g.)_ Open a requisition with some lines
- [ ] _(e.g.)_ Make a couple invoices supplying some amount of those lines
- [ ] _(e.g.)_ Review that "issued" column is the sum of the amount already issued in invoices for this requisition

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

2024-11-19 22:21 UTC, myspace20 commented
@roxy-dao I need a review on this.

2024-11-21 21:24 UTC, CarlosNZ requested changes
Hi, thanks for this, it's working as you intended.

However, I think the problem here is that it doesn't make sense to be able to turn *off* all columns.

Also, there is some additional confusion caused by the incorrect labelling of this originally -- it said "Select / unselect all columns", but what it actually did was toggle the column that should be labelled "Select / unselect all *rows*", which is what this column is used for in the actual tables.

I think the correct behaviour should be as follows:

- The column label should be "Select / unselect all rows"
- In the column selection drop-down, this column (probably) should not be visible (i.e it's always on and we don't refer to it at all)
- If (and only if) there is any columns hidden, then in the selection drop-down, there should be a button/link to "Restore all columns" which resets all columns to visible. Not sure about the UI design here, but it needs to be fairly unobtrusive and not clutter the UI (perhaps we need a mockup from @mariyamsupply before we go any further?)
- There should be no option to hide all columns, it's purely a "restore" functionality.

Maybe wait till we get some design consensus on this before progressing further?

2024-11-24 20:44 UTC, mark-prins commented
Thanks @CarlosNZ I think you've summarised the requirements nicely. 
I was originally thinking to have a show/hide all columns option, but you're right, that hiding all columns makes little sense. It only helps if you want to show only a couple of columns. without the hide all option you have to manually hide each column which is pretty tedious. 

Agree with the first two changes - and I think there's a valid case for having a show/hide all option. happy to go with that or the 'restore' option. That could just be a standard link style, but yeah, will leave that for @mariyamsupply

2024-11-27 23:17 UTC, mariyamsupply commented
Now that I understand that 'select/unselect' is the name for the checkbox, not the action, I think it's actually shouldn't be on the list.
the checkbox is a function for actions, not the data. I would vote for: 
- we have 'select/hide all columns', 
- we don't have the checkbox column on the list
- if the last column (or all columns) are unselected we hide the column with check-boxes as well

2024-12-02 22:02 UTC, mariyamsupply commented
Potential design for the rearranging columns icon (after we remove Actions dropdown)
<img width="1024" alt="arrange columns" src="https://github.com/user-attachments/assets/0abae342-06e6-4aab-a183-dd1c2009ab48">

2024-12-15 20:18 UTC, roxy-dao commented
@myspace20  Hi are you still interested in working on this issue?

2024-12-17 15:08 UTC, myspace20 commented
I am a little busy right now

2024-12-31 00:10 UTC, mark-prins commented
I'm taking over! superceded by #5907

2024-12-31 00:10 UTC, closed without merging