add XOF currency
msupply-foundation/open-msupply pull request #5786
Opened 2024-12-12 23:45 UTC by zachariah-at-msupply

Fixes # 5777

# 👩🏻‍💻 What does this PR do?

Adds XOF currency.

## 💌 Any notes for the reviewer?

Believe in yourself 

;)

# 🧪 Testing

- [ ] In 4D msupply navigator go to special>stores>select the store you want>preferences>tick "Store: able to issue in foreign currency".
- [ ] Log in to that store in open mSupply and go to distribution>outbound shipment.
- [ ] Create a new outbound shipment to PF0-15 (or any other thing that's not a store).
- [ ] Add an item to that shipment, of something that you have some stock of, and put a pack qty issued in that column.
- [ ] Click ok to get back to the page you can add medecines from, and click more in the top right corner.
- [ ] Scroll down the side bar that opens up and edit the 'Foreign Currency' field.
- [ ] Change the currency to XOF, and observe that
        1. the unit is CFA
        2. the precision is 0

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ x ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  3.

2024-12-12 23:50 UTC, roxy-dao requested changes
Thanks for the changes Zachariah! 

There were a few extra requests in the issue: 

Add XAF and CDF, the symbol is the code. and no precision (:

2024-12-12 23:50 UTC, roxy-dao commented on client/packages/common/src/intl/currency/currency.ts
> +        symbol: 'CFA',
Sorry the symbol is XOF

2024-12-13 00:00 UTC, zachariah-at-msupply commented
I didn't see Mark's comments until now, I'll add XAF and CDF as he asked in the original issue and commit again.

2024-12-13 00:01 UTC, roxy-dao commented
> I didn't see Mark's comments until now, I'll add XAF and CDF as he asked in the original issue and commit again before concluding the PR

You have to wait for approval before merging...

2024-12-13 00:25 UTC, merged