5826-Plugin-base
msupply-foundation/open-msupply pull request #5892
Opened 2024-12-23 20:25 UTC by andreievg

Fixes #5826

# 👩🏻‍💻 What does this PR do?

Add base plugin provider with BoaJS as the engine for JS plugins.

Only AMC pluging is implemented, although suggested quantity is mentioned in the issue, this will be done in follow up PRs.

Changed the plugin provider slightly, to try to reduce number of places to change when adding new plugin. 

Also tried to balance out funky/complex rust types with readability and dryness.

## 💌 Any notes for the reviewer?

There are quite a few TODO, they would be captured in the epic (carry over).

I would love to do internal docs, but the shape might still change a little bit, once it's finalised will get into docs

# 🧪 Testing

- [ ] _(e.g.)_ Central Sync server with 1 Legacy Desktop remote site and 1 OMS remote site running this PR
- [ ] _(e.g.)_ This sample datafile: _google drive link_
- [ ] _(e.g.)_ Open a requisition with some lines
- [ ] _(e.g.)_ Make a couple invoices supplying some amount of those lines
- [ ] _(e.g.)_ Review that "issued" column is the sum of the amount already issued in invoices for this requisition

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

2025-01-06 04:46 UTC, jmbrunskill reviewed
Looking good Andrei.

Keen to talk about a couple of things in person.

1. Defining what we pass to plugins, how do we decide what to expose and how do we document it? `Filter` feels dodgy to expose to me, but maybe it's ok as it is in the graphql...
2. Do we need to provide some kinds of backwards compatibility, if interfaces change for example?

2025-01-06 04:46 UTC, jmbrunskill commented on server/server/src/upload_plugin.rs
> +    r#type: PluginType,
I assume you're refine this a bit in a later PR?
Or at least add some docs about what these types are?
I think `variant_type` could have a better name but struggling to thing of one right now, maybe `plugin-technology`? Could also just leave that off until we actually have a different type?

2025-01-06 04:46 UTC, jmbrunskill commented on server/server/src/upload_plugin.rs
> +    let bundle_base64 = BASE64_STANDARD.encode(fs::read(static_file.to_path_buf()).unwrap());
Just a random thought, but do we actually need to BASE64 this? Can't it just be a string?
Not sure what the advantages/disadvantages would be though...

2025-01-06 04:46 UTC, jmbrunskill commented on server/service/src/backend_plugin/boajs/call_plugin.rs
> +        .unwrap();
Is this unwrap safe? Should probably handle this being missing right?

2025-01-06 04:46 UTC, jmbrunskill commented on server/service/src/backend_plugin/boajs/methods/log.rs
> +            info!("from js {:#?}", args);
Would be nice to handle strings here as a special case to make the log a bit cleaner.

```
ebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36" 0.039822
2025-01-06 17:16:32.156279000 [INFO ] <service::backend_plugin::boajs::methods::log:10>:from js [
    String(
        "Running SQL query",
    ),
]
```

2025-01-06 04:46 UTC, jmbrunskill commented on server/service/src/backend_plugin/examples/amc/amc.js
> +    const item_ids = filter.item_id.equal_any;
What if the filter is more complex?
I think our interfaces should be much more closely controlled for plugins?
Passing a filter object seems a bit to easy to screw up? Although I guess it's up to the plugin developer to know what to expect...

It's a bit of a higher level question about how we'll defined out plugin interfaces, would be keen for a discussion...

2025-01-07 03:51 UTC, jmbrunskill commented on server/server/src/upload_plugin.rs
> +    let bundle_base64 = BASE64_STANDARD.encode(fs::read(static_file.to_path_buf()).unwrap());
Discussed in person, happy to keep base64

2025-01-07 03:52 UTC, jmbrunskill requested changes
Happy to merge once we have 

- [ ] https://github.com/msupply-foundation/open-msupply/pull/5929 (or similar)
- [ ] Fix the unwraps()

2025-01-27 21:15 UTC, andreievg commented on server/service/src/backend_plugin/boajs/methods/log.rs
> +            info!("from js {:#?}", args);
> Would be nice to handle strings here as a special case to make the log a bit cleaner.

Logging is only for devs, yes it would be great to handle a bit better here, but it's could be any array of args, and extracting string and formatting them differently seems like quite a bit of code. I feel like the display is adequate for the target consumer. 

Please let me know if you feeling strong on this one

2025-01-27 21:18 UTC, andreievg commented
> Do we need to provide some kinds of backwards compatibility, if interfaces change for example?

Versioning would work similar to the reports, we will try to be backwards compatible but there is a chance that interface would change, which would require a new version, will explain in full plugin documentation (in the epic versioning is mentioned a few time, i think that's should capture an action for this comment)

2025-01-27 21:34 UTC, andreievg commented on server/service/src/backend_plugin/boajs/call_plugin.rs
> +        .unwrap();
Thanks, i missed this: 7563e8d975642cbad1cc7878b70b05a8563cc22c

2025-01-29 01:25 UTC, jmbrunskill approved these changes
Thanks for the update @andreievg 
I haven't tested again, but looks good. Not sure if you're ready to merge but happy for you to merge if you're ready...

2025-01-29 03:15 UTC, andreievg commented
Thanks for reviews @jmbrunskill !
It's ready to merge yeah, there is test error but it's fixed in downstream PRS

2025-01-29 03:15 UTC, merged