5804 PR 1 update actions footer across all detail view tables
msupply-foundation/open-msupply pull request #5894
Opened 2024-12-23 21:21 UTC by noel-yeldos

Partly Fixes #5804 

# 👩🏻‍💻 What does this PR do?
Update detail view tables with new action footer and remove actions dropdown from toolbar.

Used actions footer component that @GeronimoJohn created and implemented it in detail view tables

Changes needed as part of GEDSI

![Screenshot 2024-12-24 at 10 10 55 AM](https://github.com/user-attachments/assets/393f80b2-25b9-49f4-a2df-d7812d4a4060)
![Screenshot 2024-12-24 at 10 11 28 AM](https://github.com/user-attachments/assets/34f7b7b4-f12e-4ca8-89e6-0895fe0eee32)
![Screenshot 2024-12-24 at 10 11 44 AM](https://github.com/user-attachments/assets/e8ccb878-8408-42b9-a327-539614e8ec5a)
![Screenshot 2024-12-24 at 10 12 04 AM](https://github.com/user-attachments/assets/c2727f38-9dd5-40bb-911f-e0cac0639e53)
![Screenshot 2024-12-24 at 10 14 28 AM](https://github.com/user-attachments/assets/0b8c215b-2cf8-4b0b-a402-0a44565f88a7)
![Screenshot 2024-12-24 at 10 14 52 AM](https://github.com/user-attachments/assets/57de3082-469b-4dd1-a37f-8fbe74020b12)
![Screenshot 2024-12-24 at 10 16 04 AM](https://github.com/user-attachments/assets/953a6851-43dc-4309-b314-485ab5b2e3f7)
![Screenshot 2024-12-24 at 10 16 31 AM](https://github.com/user-attachments/assets/51d9d813-cc7b-4f10-bc9b-9ce4b400e5d3)

## 💌 Any notes for the reviewer?

I have added some questions as comments in the following places:
```client/packages/common/src/ui/layout/tables/columns/PaginationRow/PaginationRow.tsx``` line 55
```client/packages/inventory/src/Stocktake/DetailView/Footer/Footer.tsx``` line 43

This is only part 1 of the fixes needed. List view tables will be done in separate PR.

# 🧪 Testing

- [ ] Open any detail view tables
- [ ] Check lines to have selected rows
- [ ] Observe actions footer 
- [ ] Test that action footer buttons work correctly

# 📃 Documentation

- [ ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
- [ ] **These areas should be updated or checked**: 
  1.
  2.

2025-01-05 21:14 UTC, lache-melvin requested changes

2025-01-05 22:32 UTC, lache-melvin commented on client/packages/inventory/src/Stocktake/DetailView/Footer/Footer.tsx
> +      onClick: openReduceToZeroModal,
should also have `isDisabled`

2025-01-05 22:32 UTC, lache-melvin commented on client/packages/invoices/src/InboundShipment/DetailView/Footer/Footer.tsx
> +      disabled: isDisabled,
per discussion, to remove

2025-01-06 03:17 UTC, noel-yeldos commented on client/packages/invoices/src/InboundShipment/DetailView/Footer/Footer.tsx
> +      disabled: isDisabled,
Fixed here c82cdcfc4bcced78a8546ae9867a6df30130d558 :)

2025-01-06 03:18 UTC, noel-yeldos commented on client/packages/inventory/src/Stocktake/DetailView/Footer/Footer.tsx
> +      onClick: openReduceToZeroModal,
Fixed here c82cdcfc4bcced78a8546ae9867a6df30130d558 :)

2025-01-06 03:29 UTC, noel-yeldos commented on client/packages/requisitions/src/ResponseRequisition/DetailView/Toolbar/Toolbar.tsx
> +// import { ToolbarDropDown } from './ToolbarDropDown';
Fixed here c055255101e0b2648940b96aa6f1aff8a28680d7

2025-01-06 03:29 UTC, noel-yeldos commented on client/packages/invoices/src/Returns/api/hooks/line/useDeleteSelectedSupplierLines.ts
> +interface DeleteSelectedSupplierLinesOutputProps {
Fixed here c055255101e0b2648940b96aa6f1aff8a28680d7

2025-01-06 03:57 UTC, noel-yeldos commented on client/packages/inventory/src/Stocktake/DetailView/Footer/Footer.tsx
> +  // Is this check needed now that actions only appear when lines are selected?
Fixed here ff2b10df5b5c6ab9db55b53ca8058241ba5f61c6 :)

2025-01-06 19:20 UTC, lache-melvin approved these changes
LGTM 🔥 Ship it!

2025-01-06 19:23 UTC, lache-melvin commented on client/packages/inventory/src/Stocktake/DetailView/Footer/Footer.tsx
> +      icon: <DeleteIcon />,
Ah, and same here! Thank you!

2025-01-06 19:53 UTC, noel-yeldos commented on client/packages/invoices/src/InboundShipment/DetailView/Footer/Footer.tsx
> +      label: t('button.delete-lines'),
Fixed here c5d1b4e4d388713ac1342c1ee046d7d78c7836f3 :)

2025-01-06 19:53 UTC, noel-yeldos commented on client/packages/inventory/src/Stocktake/DetailView/Footer/Footer.tsx
> +      icon: <DeleteIcon />,
Fixed here c5d1b4e4d388713ac1342c1ee046d7d78c7836f3

2025-01-06 20:45 UTC, lache-melvin approved these changes
🚀

2025-01-06 21:41 UTC, merged